"""core/ops/stateless_functional_bridge.py — Stateless Functional Bridge

Decouples in-memory logic execution from live morphogenetic file updates on disk
by using an Ephemeral Logic Router to re-import/reload AST definitions prior to execution
while keeping runtime state decoupled inside persistent containers.
"""
import importlib
import sys
import logging
from typing import Any, Dict, Tuple

logger = logging.getLogger("Aura.Ops.FunctionalBridge")


class EphemeralLogicRouter:
    """Decouples active operational states from changing code layouts on disk."""

    @staticmethod
    def execute_mutated_logic(module_path: str, function_name: str, state_payload: Dict[str, Any], *args, **kwargs) -> Tuple[Dict[str, Any], Any]:
        """Forces cache clearance to catch AST shifts generated by Morphogenesis prior to execution.
        
        Args:
            module_path: Full dotted import path of the target module (e.g. 'core.morphogenesis.tactical_policy').
            function_name: Name of the function to execute.
            state_payload: A dictionary of state variables passed to the function.
            
        Returns:
            A tuple of (updated_state_dict, result).
        """
        # Force cache clearance to catch AST shifts generated by Morphogenesis
        if module_path in sys.modules:
            try:
                importlib.reload(sys.modules[module_path])
            except Exception as e:
                logger.error(f"Failed to reload morphic module '{module_path}': {e}")
                raise e
        else:
            try:
                importlib.import_module(module_path)
            except Exception as e:
                logger.error(f"Failed to import morphic module '{module_path}': {e}")
                raise e
            
        target_module = sys.modules[module_path]
        target_callable = getattr(target_module, function_name)
        
        # Execute the newly compiled code layout using the historical state container
        updated_state, execution_result = target_callable(state_payload, *args, **kwargs)
        return updated_state, execution_result
