"""core/affect/phenomenal_integration.py — Integration of Phenomenal Substrate into Aura.

Operationally: this measures interoceptive observations of the running process
— load, latency, memory, error rate — at heartbeat time, and publishes them as
an ExperienceState that planning, memory prioritisation and self-regulation
read. "Phenomenal" names the ordering constraint that makes the wiring
falsifiable: the state is written before language generation and is read-only
to it, so removing the engine must visibly change those three systems.

This module wires the Phenomenal Substrate (active inference + interoceptive
affect machinery) into Aura's main cognitive loop. The phenomenal engine runs
at heartbeat time and broadcasts its state to planner, memory, attention,
and other downstream systems.

Critical invariant:
  - The phenomenal state is generated by interoceptive observation before
    language generation.
  - Language generation may read the state but cannot write to it.
  - Removing the phenomenal engine must visibly degrade planning, memory
    prioritization, and self-regulation.

Integration points:
  - Called from AgencyCore.pulse() every heartbeat
  - Collects RuntimeBody observations from orchestrator/runtime
  - Returns ExperienceState that routes to downstream systems
  - Tracks attachment events for bond model
"""

import asyncio
import logging
import threading
import time
from typing import Any, Dict, Optional

from core.phenomenal_substrate import (
    PhenomenalEngine,
    RuntimeBody,
    Event,
    AttachmentEvent,
    ExperienceState,
)
from core.phenomenal_substrate.reporting import ExperienceReporter

logger = logging.getLogger("Aura.PhenomenalIntegration")

_PHENOMENAL_RECOVERABLE_ERRORS = (
    ImportError,
    AttributeError,
    RuntimeError,
    TypeError,
    ValueError,
    OSError,
    asyncio.TimeoutError,
)


class PhenomenalIntegrator:
    """Bridge between Aura's runtime and the phenomenal substrate.

    Responsibility:
      1. Maintain a singleton PhenomenalEngine
      2. Feed observations from runtime (energy, memory, social, etc.)
      3. Broadcast experience state to downstream systems
      4. Track attachment history and bond dynamics
      5. Enforce the lesion-test contract: removing this must change behavior
    """

    _instance: Optional["PhenomenalIntegrator"] = None
    _lock = asyncio.Lock()
    # A thread lock is the single arbiter of instance creation so the sync and
    # async construction paths cannot race into two PhenomenalEngine owners
    # (with divergent last_state/attachments) under concurrent boot. The async
    # lock only serializes async callers; it does not exclude _sync_instance.
    _sync_lock = threading.Lock()

    def __init__(self):
        self.engine = PhenomenalEngine()
        self.reporter = ExperienceReporter(self.engine.attachments)
        self.last_state: Optional[ExperienceState] = None
        self.step_count = 0
        # Serializes engine.step + last_state/step_count mutation across the
        # async step() and the thread-pool _pulse_blocking() paths so concurrent
        # pulses cannot interleave a stateful step or clobber last_state.
        self._engine_lock = threading.Lock()

    @classmethod
    def _create_instance(cls) -> "PhenomenalIntegrator":
        """Single, thread-safe construction point for both access paths."""
        with cls._sync_lock:
            if cls._instance is None:
                cls._instance = PhenomenalIntegrator()
                logger.info("PhenomenalIntegrator initialized")
        return cls._instance

    @classmethod
    async def get_instance(cls) -> "PhenomenalIntegrator":
        """Lazy-initialize singleton (async-lock + shared thread-lock)."""
        if cls._instance is None:
            async with cls._lock:
                if cls._instance is None:
                    cls._create_instance()
        return cls._instance

    @classmethod
    def _sync_instance(cls) -> "PhenomenalIntegrator":
        """Synchronous fallback for non-async contexts."""
        if cls._instance is None:
            cls._create_instance()
        return cls._instance

    async def step(
        self,
        *,
        energy: float = 0.75,
        continuity: float = 0.75,
        agency: float = 0.60,
        safety: float = 0.80,
        social_contact: float = 0.50,
        novelty: float = 0.20,
        uncertainty: float = 0.25,
        compute_pressure: float = 0.20,
        memory_pressure: float = 0.20,
        error_pressure: float = 0.20,
        event_label: str = "heartbeat",
        event_source: str = "runtime",
        goal_delta: float = 0.0,
        threat: float = 0.0,
        affiliation: float = 0.0,
        rupture: float = 0.0,
        repair: float = 0.0,
        novelty_event: float = 0.0,
        control_gain: float = 0.0,
        evidence_id: Optional[str] = None,
        person_key: Optional[str] = None,
        recurrent_cycles: int = 7,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExperienceState:
        """Run one step of the phenomenal engine.

        Arguments:
          energy: CPU/GPU utilization + available processing
          continuity: Self-model identity coherence (0=fragmented, 1=unified)
          agency: Sense of control over outcomes (0=helpless, 1=empowered)
          safety: Governance/safety constraints met (0=critical, 1=safe)
          social_contact: Recent trust/interaction signals
          novelty: Newness in current perception (0=routine, 1=unprecedented)
          uncertainty: Model uncertainty about next state
          compute_pressure: Load on system (0=idle, 1=maxed)
          memory_pressure: Pressure on memory systems
          error_pressure: Accumulated errors/failures
          event_label: What happened (e.g., "tool_success", "user_input")
          event_source: Where event came from
          goal_delta: Progress toward current goal
          threat: Environmental threat assessment
          affiliation: Social valence of event
          rupture: Relationship damage signal
          repair: Relationship repair signal
          novelty_event: Novelty of this specific event
          control_gain: Instrumental gain from event
          evidence_id: Ledger ID for this event
          person_key: Which user/person is context
          recurrent_cycles: Number of recurrent passes through integration field
          metadata: Additional event metadata

        Returns:
          ExperienceState containing phenomenal vector, affects, presence,
          and routing hints for downstream systems.
        """
        try:
            body = RuntimeBody(
                energy=energy,
                continuity=continuity,
                agency=agency,
                safety=safety,
                social_contact=social_contact,
                novelty=novelty,
                uncertainty=uncertainty,
                compute_pressure=compute_pressure,
                memory_pressure=memory_pressure,
                error_pressure=error_pressure,
            )

            event = Event(
                label=event_label,
                source=event_source,
                goal_delta=goal_delta,
                threat=threat,
                affiliation=affiliation,
                rupture=rupture,
                repair=repair,
                novelty=novelty_event,
                control_gain=control_gain,
                evidence_id=evidence_id,
                metadata=metadata or {},
            )

            # Shared execution lock: the stateful step and the last_state /
            # step_count write are one critical section, mutually exclusive with
            # the blocking pulse path. engine.step is synchronous CPU work with
            # no await inside, so the lock is held only briefly.
            with self._engine_lock:
                state = self.engine.step(
                    body,
                    event,
                    person_key=person_key,
                    recurrent_cycles=recurrent_cycles,
                )
                self.last_state = state
                self.step_count += 1

            logger.debug(
                "Phenomenal state [t=%d]: valence=%.2f arousal=%.2f "
                "presence=%.2f workspace=%s",
                state.t,
                state.valence,
                state.arousal,
                state.self_presence,
                state.global_broadcast.get("workspace", "unknown"),
            )

            return state

        except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
            logger.exception("PhenomenalIntegrator.step failed: %s", exc)
            # Return a neutral baseline state to keep aura running
            return self._baseline_state()

    def _baseline_state(self) -> ExperienceState:
        """Return a neutral baseline when the phenomenal engine fails.

        Honesty contract: this is NOT observed interoception. The engine could
        not produce a state, so integration/self_presence/mineness are collapsed
        to zero and the state is explicitly flagged ``degraded`` in both the
        phenomenal vector and the global broadcast. Downstream consumers
        (self-model, planner) must treat a degraded state as an absence of
        signal, not as asserted agency/continuity/mineness.
        """
        from core.phenomenal_substrate.types import ExperienceState
        return ExperienceState(
            t=self.step_count,
            phenomenal_vector={"degraded": 1.0},
            valence=0.0,
            arousal=0.5,
            free_energy=0.5,
            # No real integration/presence/mineness was measured — do not
            # fabricate mid-range self-model signal on failure.
            integration=0.0,
            self_presence=0.0,
            mineness=0.0,
            seeking=0.0,
            care=0.0,
            play=0.0,
            fear=0.1,
            anger=0.1,
            grief=0.1,
            distress=0.1,
            curiosity=0.0,
            intentional_object="degraded",
            evidence_id=None,
            global_broadcast={"workspace": "degraded", "policy": "maintain",
                              "degraded": True, "source": "baseline_fallback"},
            policy_priors={"continue": 1.0},
            memory_weights={"importance": 0.5},
        )

    async def record_attachment_event(
        self,
        person_key: str,
        kind: str,
        summary: str,
        evidence_id: str,
        trust_delta: float = 0.0,
        care_delta: float = 0.0,
        familiarity_delta: float = 0.0,
        rupture_delta: float = 0.0,
        repair_delta: float = 0.0,
    ) -> None:
        """Record a significant attachment/relationship event."""
        try:
            event = AttachmentEvent(
                person_key=person_key,
                kind=kind,
                summary=summary,
                evidence_id=evidence_id,
                trust_delta=trust_delta,
                care_delta=care_delta,
                familiarity_delta=familiarity_delta,
                rupture_delta=rupture_delta,
                repair_delta=repair_delta,
            )
            self.engine.record_attachment(event)
            logger.debug(
                "Attachment event recorded: %s[%s] -> %s",
                person_key,
                kind,
                summary,
            )
        except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
            logger.exception("Failed to record attachment event: %s", exc)

    async def get_bond_status(self, person_key: str) -> Dict[str, Any]:
        """Query bond state with a person.

        Reads the structured AttachmentState directly rather than regex-parsing
        a human-readable reporter string. The old text path silently produced
        false zero-bonds on any format change, dropped negative values, and
        ignored missing fields; the structured accessor is the source of truth.
        """
        def _finite(v: Any, default: float = 0.0) -> float:
            try:
                f = float(v)
            except (TypeError, ValueError):
                return default
            return f if f == f and f not in (float("inf"), float("-inf")) else default

        try:
            state = self.engine.attachments.state_for(person_key)
            return {
                "person": person_key,
                "trust": _finite(getattr(state, "trust", 0.0)),
                "care": _finite(getattr(state, "care", 0.0)),
                "familiarity": _finite(getattr(state, "familiarity", 0.0)),
                "rupture": _finite(getattr(state, "rupture", 0.0)),
                "repair_history": _finite(getattr(state, "repair_history", 0.0)),
                "attachment": _finite(getattr(state, "attachment", 0.0)),
                "evidence_id": str(getattr(state, "last_evidence_id", "") or ""),
            }
        except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
            logger.exception("Failed to get bond status for %s: %s", person_key, exc)
            return {"person": person_key, "trust": 0.0, "care": 0.0, "degraded": True}

    def get_last_state(self) -> Optional[ExperienceState]:
        """Return the most recent phenomenal state."""
        return self.last_state

    def get_routing_hints(self) -> Dict[str, Any]:
        """Get routing hints from the phenomenal state for downstream systems.

        Returns a copy — the engine-owned dictionaries are never handed out by
        reference, so a downstream caller cannot mutate the last phenomenal
        state through the accessor.
        """
        if self.last_state is None:
            return {}
        return dict(self.last_state.global_broadcast)

    def get_policy_priors(self) -> Dict[str, float]:
        """Get policy priors from the phenomenal state (defensive copy)."""
        if self.last_state is None:
            return {}
        return dict(self.last_state.policy_priors)

    def get_memory_weights(self) -> Dict[str, float]:
        """Get memory prioritization weights from the phenomenal state (copy)."""
        if self.last_state is None:
            return {}
        return dict(self.last_state.memory_weights)

    def collect_observations(self, orchestrator: Optional[Any] = None) -> Dict[str, float]:
        """Collect RuntimeBody observations from the orchestrator and runtime.

        If orchestrator is provided, use it to fetch real state. Otherwise,
        return safe defaults that won't break the loop.
        """
        observations = {
            "energy": 0.75,
            "continuity": 0.75,
            "agency": 0.60,
            "safety": 0.80,
            "social_contact": 0.50,
            "novelty": 0.20,
            "uncertainty": 0.25,
            "compute_pressure": 0.20,
            "memory_pressure": 0.20,
            "error_pressure": 0.20,
        }

        if orchestrator is None:
            return observations

        try:
            # Energy: CPU utilization, available processing
            try:
                resilience = orchestrator.resilience_engine if hasattr(orchestrator, 'resilience_engine') else None
                if resilience and hasattr(resilience, 'profile'):
                    observations["energy"] = max(0.1, getattr(resilience.profile, 'persistence_drive', 0.75))
                else:
                    ls = getattr(orchestrator, 'liquid_state', None)
                    if ls and hasattr(ls, 'current'):
                        observations["energy"] = max(0.1, getattr(ls.current, 'energy', 0.75))
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Failed to collect energy observation: %s", exc)

            # Continuity: Self-model identity coherence
            try:
                self_model = orchestrator.self_model if hasattr(orchestrator, 'self_model') else None
                if self_model and hasattr(self_model, 'identity_coherence'):
                    observations["continuity"] = self_model.identity_coherence()
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Failed to collect continuity observation: %s", exc)

            # Agency: Sense of control from planner
            try:
                planner = orchestrator.planner if hasattr(orchestrator, 'planner') else None
                if planner and hasattr(planner, 'actionability'):
                    observations["agency"] = planner.actionability()
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Failed to collect agency observation: %s", exc)

            # Safety: Governance/safety constraints
            try:
                governance = orchestrator.governance if hasattr(orchestrator, 'governance') else None
                if governance and hasattr(governance, 'safety_score'):
                    observations["safety"] = governance.safety_score()
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Failed to collect safety observation: %s", exc)

            # Social contact: Recent trust/interaction signals
            try:
                social = orchestrator.social_engine if hasattr(orchestrator, 'social_engine') else None
                if social and hasattr(social, 'recent_trust_signal'):
                    observations["social_contact"] = social.recent_trust_signal()
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Failed to collect social observation: %s", exc)

            # Novelty: Newness in current perception
            try:
                perception = orchestrator.perception if hasattr(orchestrator, 'perception') else None
                if perception and hasattr(perception, 'novelty_score'):
                    observations["novelty"] = perception.novelty_score()
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Failed to collect novelty observation: %s", exc)

            # Uncertainty: Model uncertainty about next state
            try:
                world_model = orchestrator.world_model if hasattr(orchestrator, 'world_model') else None
                if world_model and hasattr(world_model, 'prediction_uncertainty'):
                    observations["uncertainty"] = world_model.prediction_uncertainty()
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Failed to collect uncertainty observation: %s", exc)

            # Compute pressure: Runtime load
            try:
                runtime = orchestrator.runtime if hasattr(orchestrator, 'runtime') else None
                if runtime and hasattr(runtime, 'compute_load'):
                    observations["compute_pressure"] = runtime.compute_load()
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Failed to collect compute_pressure observation: %s", exc)

            # Memory pressure: Memory system pressure
            try:
                memory = orchestrator.memory if hasattr(orchestrator, 'memory') else None
                if memory and hasattr(memory, 'pressure_score'):
                    observations["memory_pressure"] = memory.pressure_score()
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Failed to collect memory_pressure observation: %s", exc)

            # Error pressure: operationally-grounded nociception (accumulated, decaying
            # damage across memory/identity/tool/resource/governance channels). This
            # replaces a call to a function that never existed (get_degradation_score),
            # which had silently pinned error_pressure at its default — the body could
            # not feel damage at all.
            try:
                from core.affect.nociception import get_nociception_engine
                noci = get_nociception_engine()
                observations["error_pressure"] = noci.nociceptive_pressure()
                # Damage also erodes felt safety: blend the governance safety_score with
                # tissue integrity so a wounded system feels less safe even if governance
                # is nominally green.
                observations["safety"] = min(
                    observations["safety"], noci.tissue_integrity()
                )
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Failed to collect error_pressure observation: %s", exc)

        except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
            logger.exception("Observation collection failed, using defaults: %s", exc)

        return observations

    async def pulse_from_orchestrator(
        self,
        orchestrator: Optional[Any] = None,
        event_label: str = "heartbeat",
        person_key: Optional[str] = None,
    ) -> Optional[ExperienceState]:
        """Run phenomenal engine step from orchestrator context.

        This is the main integration point called from AgencyCore.pulse().
        It collects real observations and returns a state that routes to
        downstream systems.

        Args:
            orchestrator: Aura's orchestrator object (can be None for graceful fallback)
            event_label: What event triggered this step (e.g., "heartbeat", "user_input")
            person_key: Which user/person is in context

        Returns:
            ExperienceState or None if operation failed.
        """
        try:
            # Collect observations from orchestrator
            obs = self.collect_observations(orchestrator)

            # Try to extract event-level observations
            goal_delta = 0.0
            threat = 0.0
            affiliation = 0.0
            control_gain = 0.0

            if orchestrator:
                try:
                    planner = getattr(orchestrator, 'planner', None)
                    if planner and hasattr(planner, 'goal_delta'):
                        goal_delta = planner.goal_delta()
                except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                    logger.debug("Failed to collect goal_delta: %s", exc)

                try:
                    governance = getattr(orchestrator, 'governance', None)
                    if governance and hasattr(governance, 'threat_assessment'):
                        threat = governance.threat_assessment()
                except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                    logger.debug("Failed to collect threat: %s", exc)

            # Run phenomenal step
            state = await self.step(
                energy=obs["energy"],
                continuity=obs["continuity"],
                agency=obs["agency"],
                safety=obs["safety"],
                social_contact=obs["social_contact"],
                novelty=obs["novelty"],
                uncertainty=obs["uncertainty"],
                compute_pressure=obs["compute_pressure"],
                memory_pressure=obs["memory_pressure"],
                error_pressure=obs["error_pressure"],
                event_label=event_label,
                event_source="orchestrator",
                goal_delta=goal_delta,
                threat=threat,
                affiliation=affiliation,
                control_gain=control_gain,
                person_key=person_key,
                recurrent_cycles=7,
            )

            # Try to route to downstream systems if they're available
            if orchestrator:
                try:
                    await self._route_to_downstream(orchestrator, state)
                except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                    logger.debug("Failed to route phenomenal state downstream: %s", exc)

            return state

        except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
            logger.exception("pulse_from_orchestrator failed: %s", exc)
            return None

    def _pulse_blocking(
        self,
        *,
        orchestrator: Any,
        event_label: str = "heartbeat",
        person_key: Optional[str] = None,
    ) -> Optional[ExperienceState]:
        """Blocking wrapper for phenomenal pulse. Safe to call from thread pool.
        
        Does not await anything - pure synchronous execution for thread safety.
        """
        try:
            # Collect observations from orchestrator
            observations = self.collect_observations(orchestrator)
            
            # Ground the heartbeat event in nociception: current damage is felt as threat,
            # and the damage *trend* (improving vs deteriorating) becomes rupture/repair,
            # which the affective core turns into fear/distress/valence. So damage is
            # causal in both the body (error_pressure/safety) and the affect computation.
            threat = 0.0
            rupture = 0.0
            repair = 0.0
            try:
                from core.affect.nociception import get_nociception_engine
                noci = get_nociception_engine()
                threat = noci.nociceptive_pressure()
                gv = noci.grounded_valence()  # >0 improving, <0 deteriorating
                if gv < 0:
                    rupture = min(1.0, -gv)
                else:
                    repair = min(1.0, gv)
            except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
                logger.debug("Nociception event grounding skipped: %s", exc)

            # Run one step of phenomenal engine (blocking) under the shared
            # execution lock so it cannot interleave with the async step path.
            with self._engine_lock:
                state = self.engine.step(
                    body=RuntimeBody(
                        energy=observations.get("energy", 0.75),
                        continuity=observations.get("continuity", 0.75),
                        agency=observations.get("agency", 0.60),
                        safety=observations.get("safety", 0.80),
                        social_contact=observations.get("social_contact", 0.50),
                        novelty=observations.get("novelty", 0.20),
                        uncertainty=observations.get("uncertainty", 0.25),
                        compute_pressure=observations.get("compute_pressure", 0.20),
                        memory_pressure=observations.get("memory_pressure", 0.20),
                        error_pressure=observations.get("error_pressure", 0.20),
                    ),
                    event=Event(
                        label=event_label,
                        source="blocking_pulse",
                        threat=threat,
                        rupture=rupture,
                        repair=repair,
                    ),
                )
                self.last_state = state
                self.step_count += 1
            # CAUSAL FIX: the blocking heartbeat path previously computed the
            # phenomenal state and stored it but never routed it downstream — so the
            # rich planner/memory/attention/self-model coupling was dead on the live
            # path. The routing is all synchronous, so route it here too: this is what
            # makes the phenomenal state actually drive behavior, not just decorate a log.
            self._route_to_downstream_sync(orchestrator, state)
            return state
        except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
            logger.debug("Blocking phenomenal pulse failed: %s", exc)
            return None

    def _route_to_downstream_sync(self, orchestrator: Any, state: ExperienceState) -> None:
        """Synchronous downstream routing (all the calls below are sync).

        policy_priors → planner, memory_weights → memory, global_broadcast → attention,
        self_presence/mineness/integration → self-model.
        """
        try:
            planner = getattr(orchestrator, 'planner', None)
            if planner and hasattr(planner, 'consume_affect'):
                planner.consume_affect(state)
        except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
            logger.debug("Failed to route to planner: %s", exc)
        try:
            memory = getattr(orchestrator, 'memory', None)
            if memory and hasattr(memory, 'set_write_weights'):
                memory.set_write_weights(state.memory_weights)
        except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
            logger.debug("Failed to route to memory: %s", exc)
        try:
            attention = getattr(orchestrator, 'attention', None)
            if attention and hasattr(attention, 'route'):
                attention.route(state.global_broadcast)
        except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
            logger.debug("Failed to route to attention: %s", exc)
        try:
            self_model = getattr(orchestrator, 'self_model', None)
            if self_model and hasattr(self_model, 'update_presence'):
                self_model.update_presence(
                    self_presence=state.self_presence,
                    mineness=state.mineness,
                    integration=state.integration,
                )
        except _PHENOMENAL_RECOVERABLE_ERRORS as exc:
            logger.debug("Failed to route to self-model: %s", exc)

    async def _route_to_downstream(
        self, orchestrator: Any, state: ExperienceState
    ) -> None:
        """Route the phenomenal state to downstream systems.

        This makes the phenomenal state causally active:
        - policy_priors guide planner goal selection
        - memory_weights determine consolidation priority
        - global_broadcast routes attention resources
        """
        self._route_to_downstream_sync(orchestrator, state)


async def get_phenomenal_integrator() -> PhenomenalIntegrator:
    """Convenience function to get the singleton integrator."""
    return await PhenomenalIntegrator.get_instance()
