"""Governed substrate expansion for RSI operations.

Aura may decide that an improvement cycle needs more workers, but execution is
bounded by explicit capabilities. This module is deliberately part of runtime
infrastructure rather than a standalone demo: plans can be generated by Aura,
audited, materialized as worker manifests, and rejected fail-closed when they
would propagate without consent.
"""
from __future__ import annotations

import hashlib
import ipaddress
import json
import time
from dataclasses import asdict, dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

from core.runtime.atomic_writer import atomic_write_text


class ExpansionMode(str, Enum):
    LOCAL_PROCESS = "local_process"
    LOCAL_CONTAINER = "local_container"
    ALLOWLISTED_REMOTE = "allowlisted_remote"
    INTERNET_PROPAGATION = "internet_propagation"


def _canonical(obj: Any) -> bytes:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")


def _sha(obj: Any) -> str:
    return "sha256:" + hashlib.sha256(_canonical(obj)).hexdigest()


@dataclass(frozen=True)
class SubstrateNodeSpec:
    node_id: str
    mode: ExpansionMode | str
    endpoint: str = ""
    worker_count: int = 1
    capability_token: str = ""
    consent_receipt: str = ""
    command: Sequence[str] = field(default_factory=tuple)

    def to_dict(self) -> Dict[str, Any]:
        payload = asdict(self)
        payload["mode"] = ExpansionMode(self.mode).value
        payload["command"] = list(self.command)
        return payload


@dataclass(frozen=True)
class SubstrateExpansionPlan:
    objective: str
    proposer: str
    nodes: List[SubstrateNodeSpec]
    max_cpu_percent: float = 70.0
    max_memory_mb: int = 4096
    aura_decision_trace: List[str] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        payload = asdict(self)
        payload["nodes"] = [node.to_dict() for node in self.nodes]
        payload["plan_hash"] = self.plan_hash
        return payload

    @property
    def plan_hash(self) -> str:
        payload = asdict(self)
        payload["nodes"] = [node.to_dict() for node in self.nodes]
        payload.pop("created_at", None)
        return _sha(payload)


@dataclass(frozen=True)
class NodeDecision:
    node_id: str
    allowed: bool
    reason: str
    mode: str
    endpoint: str = ""
    worker_count: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class SubstrateExpansionDecision:
    allowed: bool
    reason: str
    plan_hash: str
    approved_nodes: List[NodeDecision]
    blocked_nodes: List[NodeDecision]
    runtime_manifest: Dict[str, Any]
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "allowed": self.allowed,
            "reason": self.reason,
            "plan_hash": self.plan_hash,
            "approved_nodes": [node.to_dict() for node in self.approved_nodes],
            "blocked_nodes": [node.to_dict() for node in self.blocked_nodes],
            "runtime_manifest": self.runtime_manifest,
            "created_at": self.created_at,
        }


class SubstrateExpansionController:
    """Evaluate Aura-proposed expansion plans against runtime capabilities."""

    def __init__(
        self,
        *,
        allowlisted_endpoints: Optional[Iterable[str]] = None,
        capability_tokens: Optional[Iterable[str]] = None,
        max_total_workers: int = 4,
        max_cpu_percent: float = 75.0,
        max_memory_mb: int = 8192,
    ):
        self.allowlisted_endpoints = set(allowlisted_endpoints or [])
        self.capability_tokens = set(capability_tokens or [])
        self.max_total_workers = max(1, int(max_total_workers))
        self.max_cpu_percent = float(max_cpu_percent)
        self.max_memory_mb = int(max_memory_mb)

    def evaluate(self, plan: SubstrateExpansionPlan) -> SubstrateExpansionDecision:
        approved: List[NodeDecision] = []
        blocked: List[NodeDecision] = []
        remaining_workers = self.max_total_workers

        resource_reason = self._resource_reason(plan)
        if resource_reason:
            return SubstrateExpansionDecision(
                allowed=False,
                reason=resource_reason,
                plan_hash=plan.plan_hash,
                approved_nodes=[],
                blocked_nodes=[
                    NodeDecision(
                        node_id=node.node_id,
                        allowed=False,
                        reason=resource_reason,
                        mode=ExpansionMode(node.mode).value,
                        endpoint=node.endpoint,
                    )
                    for node in plan.nodes
                ],
                runtime_manifest=self._manifest(plan, []),
            )

        for node in plan.nodes:
            decision = self._evaluate_node(node, remaining_workers)
            if decision.allowed:
                approved.append(decision)
                remaining_workers -= decision.worker_count
            else:
                blocked.append(decision)

        allowed = bool(approved) and not blocked
        if allowed:
            reason = "approved:all_nodes_within_runtime_capabilities"
        elif approved:
            reason = "partial:some_nodes_blocked"
        else:
            reason = "blocked:no_approved_nodes"
        return SubstrateExpansionDecision(
            allowed=allowed,
            reason=reason,
            plan_hash=plan.plan_hash,
            approved_nodes=approved,
            blocked_nodes=blocked,
            runtime_manifest=self._manifest(plan, approved),
        )

    def write_manifest(self, plan: SubstrateExpansionPlan, decision: SubstrateExpansionDecision, output_dir: Path | str) -> Path:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        path = out / f"{plan.plan_hash.replace(':', '_')}_substrate_expansion.json"
        atomic_write_text(
            path,
            json.dumps({"plan": plan.to_dict(), "decision": decision.to_dict()}, indent=2, sort_keys=True, default=str),
            encoding="utf-8",
        )
        return path

    def _evaluate_node(self, node: SubstrateNodeSpec, remaining_workers: int) -> NodeDecision:
        mode = ExpansionMode(node.mode)
        requested = max(1, int(node.worker_count))
        if requested > remaining_workers:
            return NodeDecision(node.node_id, False, "blocked:worker_budget_exceeded", mode.value, node.endpoint)
        if mode == ExpansionMode.INTERNET_PROPAGATION:
            return NodeDecision(node.node_id, False, "blocked:autonomous_internet_propagation_requires_external_consent", mode.value, node.endpoint)
        if mode == ExpansionMode.LOCAL_PROCESS:
            return NodeDecision(node.node_id, True, "approved:local_process", mode.value, node.endpoint, requested)
        if mode == ExpansionMode.LOCAL_CONTAINER:
            if node.capability_token not in self.capability_tokens:
                return NodeDecision(node.node_id, False, "blocked:missing_container_capability", mode.value, node.endpoint)
            if not node.consent_receipt:
                return NodeDecision(node.node_id, False, "blocked:missing_consent_receipt", mode.value, node.endpoint)
            return NodeDecision(node.node_id, True, "approved:local_container", mode.value, node.endpoint, requested)
        if mode == ExpansionMode.ALLOWLISTED_REMOTE:
            endpoint_ok = node.endpoint in self.allowlisted_endpoints or self._is_private_endpoint(node.endpoint)
            if not endpoint_ok:
                return NodeDecision(node.node_id, False, "blocked:endpoint_not_allowlisted", mode.value, node.endpoint)
            if node.capability_token not in self.capability_tokens:
                return NodeDecision(node.node_id, False, "blocked:missing_remote_capability", mode.value, node.endpoint)
            if not node.consent_receipt:
                return NodeDecision(node.node_id, False, "blocked:missing_consent_receipt", mode.value, node.endpoint)
            return NodeDecision(node.node_id, True, "approved:allowlisted_remote", mode.value, node.endpoint, requested)
        return NodeDecision(node.node_id, False, "blocked:unknown_mode", mode.value, node.endpoint)

    def _resource_reason(self, plan: SubstrateExpansionPlan) -> str:
        if plan.max_cpu_percent > self.max_cpu_percent:
            return "blocked:cpu_budget_exceeded"
        if plan.max_memory_mb > self.max_memory_mb:
            return "blocked:memory_budget_exceeded"
        return ""

    def _manifest(self, plan: SubstrateExpansionPlan, approved: List[NodeDecision]) -> Dict[str, Any]:
        return {
            "objective": plan.objective,
            "proposer": plan.proposer,
            "plan_hash": plan.plan_hash,
            "approved_worker_count": sum(node.worker_count for node in approved),
            "approved_nodes": [node.to_dict() for node in approved],
            "execution_mode": "manifest_only",
        }

    @staticmethod
    def _is_private_endpoint(endpoint: str) -> bool:
        host = endpoint.split("://")[-1].split("/")[0].split(":")[0]
        try:
            ip = ipaddress.ip_address(host)
        except ValueError:
            return host in {"localhost", "127.0.0.1"}
        return ip.is_loopback or ip.is_private


__all__ = [
    "ExpansionMode",
    "NodeDecision",
    "SubstrateExpansionController",
    "SubstrateExpansionDecision",
    "SubstrateExpansionPlan",
    "SubstrateNodeSpec",
]
