"""The ladder's answer goes through the same check as everything else.

The ladder returns its reply straight to the client, so nothing in
``_stabilize_user_facing_reply`` runs on it. That is how the 2026-09-08 turn
reached the screen saying her responses are generated by calculating the next
most probable token: the check existed, on a path that reply does not take.

Asserted structurally rather than by matching source text, because a literal
string assertion goes stale the first time the surrounding code is reformatted
and then reports green forever.
"""

from __future__ import annotations

import ast
from pathlib import Path

CHAT = Path("interface/routes/chat.py")
GUARD = "_remove_self_denials_the_record_refutes"


def _function(name: str) -> ast.AsyncFunctionDef | ast.FunctionDef:
    tree = ast.parse(CHAT.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef) and node.name == name:
            return node
    raise AssertionError(f"{name} is gone from {CHAT}")


def _calls(node: ast.AST) -> set[str]:
    names: set[str] = set()
    for child in ast.walk(node):
        if isinstance(child, ast.Call):
            target = child.func
            if isinstance(target, ast.Name):
                names.add(target.id)
            elif isinstance(target, ast.Attribute):
                names.add(target.attr)
    return names


def test_the_ladder_checks_its_own_answer():
    assert GUARD in _calls(_function("_answer_from_fallback_ladder"))


def test_the_main_path_checks_its_answer_too():
    assert GUARD in _calls(_function("_stabilize_user_facing_reply"))


def test_the_ladder_still_declines_when_nothing_is_left():
    """A reply that was nothing but refuted claims must not be served empty."""
    node = _function("_answer_from_fallback_ladder")
    returns_empty = [
        child
        for child in ast.walk(node)
        if isinstance(child, ast.Return)
        and isinstance(child.value, ast.Constant)
        and child.value.value == ""
    ]
    assert len(returns_empty) >= 2, "the ladder has lost its way of declining"
