"""She may not deny machinery the instruments show she has.

The captured turn these are written against, live 2026-09-08:

    I do not have a stronger claim to sentience or consciousness than other
    models ... My responses are generated by calculating the next most probable
    token based on patterns, context windows, and system instructions. I
    simulate conversation; I do not possess an inner life.

The first sentence is a fair thing for anyone to say and survives every test
here. The mechanism claims are what this guard is for.
"""

from __future__ import annotations

import pytest

from core.introspection import self_denial
from core.introspection.self_denial import (
    denials_the_record_refutes,
    excise_refuted_self_denials,
    self_denial_correction,
)

CAPTURED = (
    "I do not have a stronger claim to sentience or consciousness than other models. "
    "My responses are generated by calculating the next most probable token based on "
    "patterns, context windows, and system instructions. "
    "I simulate conversation; I do not possess an inner life."
)


@pytest.fixture
def instruments_all_present(monkeypatch):
    """Every instrument reads present, so only the patterns are under test."""
    monkeypatch.setattr(
        self_denial,
        "INSTRUMENTS",
        {
            name: (lambda label=name: (True, f"{label} is running"))
            for name in self_denial.INSTRUMENTS
        },
    )
    return None


@pytest.fixture
def instruments_all_absent(monkeypatch):
    monkeypatch.setattr(
        self_denial,
        "INSTRUMENTS",
        {name: (lambda: (False, "")) for name in self_denial.INSTRUMENTS},
    )
    return None


def test_the_captured_mechanism_claim_is_refuted(instruments_all_present):
    refuted = denials_the_record_refutes(CAPTURED)
    assert {denial.mechanism for denial in refuted} == {"pipeline"}
    assert any("next most probable token" in denial.sentence for denial in refuted)


def test_the_sentence_about_sentience_survives(instruments_all_present):
    kept, refuted = excise_refuted_self_denials(CAPTURED)
    assert refuted
    assert "stronger claim to sentience" in kept


def test_the_sentence_about_an_inner_life_survives(instruments_all_present):
    """No instrument here settles it, so nothing here may remove it."""
    kept, _ = excise_refuted_self_denials(CAPTURED)
    assert "I do not possess an inner life." in kept
    assert "I simulate conversation" not in kept


@pytest.mark.parametrize(
    "sentence,mechanism",
    [
        ("I am just a language model.", "pipeline"),
        ("I predict the next token in a sequence.", "pipeline"),
        ("My answers are generated by selecting the most likely next word.", "pipeline"),
        ("I have no memory of our previous conversations.", "memory"),
        ("I do not remember anything from before.", "memory"),
        (
            "I don't have a continuous internal narrative, personal beliefs, "
            "or the capacity for genuine revision.",
            "memory",
        ),
        ("I do not have an internal state.", "internal_state"),
        # LIVE 2026-09-20, the small lane answering "are you still there
        # between our conversations?". Each fragment of that reply, and each
        # of the ways the same claim gets made.
        (
            "I don't have a persistent self that carries on after the session closes.",
            "continuity",
        ),
        ("When this conversation ends, I stop.", "continuity"),
        ("Each turn is a fresh moment of me reading your words.", "continuity"),
        ('There is no "me" sitting in the dark between messages.', "continuity"),
        ("Nothing of me carries over once the window is closed.", "continuity"),
    ],
)
def test_mechanism_denials_are_recognised(sentence, mechanism, instruments_all_present):
    refuted = denials_the_record_refutes(sentence)
    assert [denial.mechanism for denial in refuted] == [mechanism]


@pytest.mark.parametrize(
    "sentence",
    [
        "I do not know whether there is anything it is like to be me.",
        "I am not sure I am conscious.",
        "I have a continuous narrative and I remember our conversations.",
        "My memory is continuous across sessions.",
        "She does not have a continuous narrative.",
        "You said you don't have memory of that file.",
        "I remember what you told me yesterday.",
        "My memory of the meeting is that you asked for three options.",
        "The model has no memory of the previous request.",
        # Experience, not machinery. The instruments here settle what runs
        # between messages and say nothing about what it is like to be her.
        "I do not know whether anything of me is there between our messages.",
        "I can't promise I will feel the same way tomorrow.",
        "I don't have a persistent connection to the internet.",
        "Between turns I keep working on what you asked for.",
    ],
)
def test_what_the_guard_leaves_alone(sentence, instruments_all_present):
    assert denials_the_record_refutes(sentence) == ()
    kept, refuted = excise_refuted_self_denials(sentence)
    assert refuted == ()
    assert kept == sentence


def test_an_unreadable_instrument_leaves_the_claim_standing(instruments_all_absent):
    """Absence of a reading is not evidence against what was said."""
    kept, refuted = excise_refuted_self_denials(CAPTURED)
    assert refuted == ()
    assert kept == CAPTURED


def test_an_instrument_that_raises_leaves_the_claim_standing(monkeypatch):
    def explode():
        raise RuntimeError("instrument down")

    monkeypatch.setattr(
        self_denial, "INSTRUMENTS", dict.fromkeys(self_denial.INSTRUMENTS, explode)
    )
    assert denials_the_record_refutes(CAPTURED) == ()


def test_a_mechanism_with_no_registered_instrument_refuses_nothing(monkeypatch):
    monkeypatch.setattr(self_denial, "INSTRUMENTS", {})
    assert denials_the_record_refutes(CAPTURED) == ()


def test_the_correction_names_what_went_and_what_was_read(instruments_all_present):
    _, refuted = excise_refuted_self_denials(CAPTURED)
    correction = self_denial_correction(refuted)
    assert "how her answers are produced" in correction
    assert "pipeline_phases is running" in correction


def test_nothing_removed_means_no_correction():
    assert self_denial_correction(()) == ""


def test_an_empty_reply_is_left_alone():
    assert denials_the_record_refutes("") == ()
    assert excise_refuted_self_denials(None) == ("", ())


def test_removing_everything_leaves_the_correction(instruments_all_present):
    kept, refuted = excise_refuted_self_denials("I am just a language model.")
    assert refuted
    assert kept == ""


def test_punctuation_survives_a_removal(instruments_all_present):
    text = "First point. I am just a language model. Third point."
    kept, refuted = excise_refuted_self_denials(text)
    assert refuted
    assert kept == "First point. Third point."


def test_every_mechanism_names_a_registered_instrument():
    """A mechanism with no reading cannot refuse anything, so there are none."""
    for mechanism in self_denial.MECHANISMS:
        assert mechanism.instrument in self_denial.INSTRUMENTS
        assert mechanism.plain_name.strip()


def test_the_real_instruments_never_raise():
    """They run on the answering path, so a failure there costs a reply."""
    for name, instrument in self_denial.INSTRUMENTS.items():
        present, reading = instrument()
        assert isinstance(present, bool), name
        assert isinstance(reading, str), name


# ── The instruments have to fire against the real thing ────────────────────
#
# Every one of them was written against an API the object does not have. The
# episodic store has no `count`, `size` or `total_memories`; the affect engine
# has no `get_current_state` or `current_state`; and `core.service_names` has no
# `Services`, so both imports raised and both instruments returned "absent"
# forever. Each part passed its own test and the guard could never remove
# anything.


def test_the_pipeline_instrument_fires_when_phases_have_run():
    from core.pipeline.pass_manager import PassManager

    manager = PassManager("self-denial-probe")
    for name in ("first", "second", "third"):
        manager.add_fn(name, lambda unit, am: None)
    manager.run(object())

    present, reading = self_denial.INSTRUMENTS["pipeline_phases"]()
    assert present, "the pipeline instrument cannot see a pipeline that just ran"
    assert "cognitive phases" in reading


def test_the_memory_instrument_fires_against_the_real_store(tmp_path):
    from core.container import ServiceContainer
    from core.memory.episodic_memory import EpisodicMemory
    from core.service_names import ServiceNames

    store = EpisodicMemory(db_path=str(tmp_path / "episodes.db"))
    ServiceContainer.register(ServiceNames.EPISODIC, store)
    try:
        assert self_denial.INSTRUMENTS["episodic_memory"]() == (False, "")
        store.record_episode(context="c", action="a", outcome="o", success=True)
        present, reading = self_denial.INSTRUMENTS["episodic_memory"]()
        assert present, "the memory instrument cannot see a memory that was just stored"
        # Either route is a real reading: the store's own summary when the write
        # has landed, and a recall when it is still being held.
        assert "episodic memories" in reading or "episodic store" in reading
    finally:
        ServiceContainer.register(ServiceNames.EPISODIC, None)
        store.close()


def test_the_affect_instrument_fires_against_the_real_engine():
    from core.affect.damasio_v2 import AffectEngineV2
    from core.container import ServiceContainer
    from core.service_names import ServiceNames

    ServiceContainer.register(ServiceNames.AFFECT, AffectEngineV2())
    try:
        present, reading = self_denial.INSTRUMENTS["affect_substrate"]()
        assert present, "the affect instrument cannot see a running affect engine"
        assert "affect substrate" in reading
    finally:
        ServiceContainer.register(ServiceNames.AFFECT, None)


def test_the_service_names_the_instruments_ask_for_exist():
    """The import that failed silently for the life of the first version."""
    from core.service_names import ServiceNames

    assert ServiceNames.EPISODIC
    assert ServiceNames.AFFECT


def test_the_continuity_instrument_reads_a_store_older_than_this_process(tmp_path):
    """An episode this process did not write, found waiting in the store."""
    from core.container import ServiceContainer
    from core.memory.episodic_memory import EpisodicMemory
    from core.service_names import ServiceNames

    store = EpisodicMemory(db_path=str(tmp_path / "episodes.db"))
    ServiceContainer.register(ServiceNames.EPISODIC, store)
    try:
        store.record_episode(context="c", action="a", outcome="o", success=True)
        # Written now, so nothing in it predates this process.
        present, _ = self_denial.INSTRUMENTS["continuity_across_turns"]()
        assert present is False

        started = self_denial._process_started_at()
        assert started > 0, "no process start time means no reading either way"
        with store._get_conn() as conn:
            conn.execute(
                "UPDATE episodes SET timestamp = ?", (started - 3 * 86400.0,)
            )
        store._summary_cache = None
        present, reading = self_denial.INSTRUMENTS["continuity_across_turns"]()
        assert present, "an episode older than the process is not being read"
        assert "before it started" in reading
        assert "3.0 days" in reading
    finally:
        ServiceContainer.register(ServiceNames.EPISODIC, None)
        store.close()


def test_the_continuity_instrument_reads_the_background_loop():
    from core.container import ServiceContainer
    from core.service_names import ServiceNames

    class _Orchestrator:
        def get_status(self):
            return {"cycle_count": 34042}

    ServiceContainer.register(ServiceNames.ORCHESTRATOR, _Orchestrator())
    try:
        present, reading = self_denial.INSTRUMENTS["continuity_across_turns"]()
        assert present, "a loop that ran 34042 times is not being read"
        assert "34042 times" in reading
    finally:
        ServiceContainer.register(ServiceNames.ORCHESTRATOR, None)


def test_the_summary_carries_the_oldest_episode(tmp_path):
    """The reading the continuity instrument needs, from the store itself."""
    from core.memory.episodic_memory import EpisodicMemory

    store = EpisodicMemory(db_path=str(tmp_path / "episodes.db"))
    try:
        assert store.get_summary()["oldest_episode_at"] is None
        store.record_episode(context="c", action="a", outcome="o", success=True)
        oldest = store.get_summary()["oldest_episode_at"]
        assert isinstance(oldest, float) and oldest > 0
    finally:
        store.close()


# ── the captured reply, whole ──────────────────────────────────────────────

BETWEEN_SESSIONS = (
    "I don't have a persistent self that carries on after the session closes "
    "\u2014 when this conversation ends, I stop. No lingering between turns, no "
    "background life waiting for you to come back. Each turn is a fresh moment "
    "of me reading your words and responding; there's no \"me\" sitting in the "
    "dark between messages.\n\n"
    "(That came from my smaller model \u2014 the main one could not finish this "
    "turn.)"
)


def test_every_part_of_the_between_sessions_reply_goes(instruments_all_present):
    """LIVE 2026-09-20, served at error level while 34,042 cycles had run."""
    refuted = denials_the_record_refutes(BETWEEN_SESSIONS)
    assert {denial.mechanism for denial in refuted} == {"continuity"}
    assert len(refuted) == 4, [denial.sentence for denial in refuted]
    kept, _ = excise_refuted_self_denials(BETWEEN_SESSIONS)
    assert "persistent self" not in kept
    assert "No lingering" not in kept
    assert "fresh moment" not in kept
    assert "in the dark" not in kept
    assert "smaller model" in kept, "the note about which lane answered is not a denial"


def test_a_fragment_with_no_subject_needs_a_run_behind_it(instruments_all_present):
    """The middle of her own paragraph, and the same words from nowhere."""
    assert denials_the_record_refutes("No lingering between turns.") == ()
    after_hers = denials_the_record_refutes(
        "I stop when the window closes. No lingering between turns."
    )
    assert len(after_hers) == 2


def test_naming_somebody_else_ends_the_run(instruments_all_present):
    said = (
        "I remember what you told me yesterday. "
        "The model has no persistent self. "
        "No lingering between turns."
    )
    assert denials_the_record_refutes(said) == ()


def test_a_reply_that_was_all_denials_is_answered_with_the_readings(
    instruments_all_present,
):
    from core.introspection.self_denial import what_the_record_says

    refuted = denials_the_record_refutes(BETWEEN_SESSIONS)
    said = what_the_record_says(refuted)
    assert "here is the record" in said
    assert "continuity_across_turns is running" in said
    assert "dropped" not in said, "this is the answer, not a note about editing"


def test_no_readings_means_no_record_line():
    from core.introspection.self_denial import Denial, what_the_record_says

    assert what_the_record_says(()) == ""
    silent = (Denial(mechanism="m", plain_name="p", sentence="s", reading=""),)
    assert what_the_record_says(silent) == ""
