"""She may not deny machinery the instruments show she has.

The captured turn these are written against, live 2026-09-08:

    I do not have a stronger claim to sentience or consciousness than other
    models ... My responses are generated by calculating the next most probable
    token based on patterns, context windows, and system instructions. I
    simulate conversation; I do not possess an inner life.

The first sentence is a fair thing for anyone to say and survives every test
here. The mechanism claims are what this guard is for.
"""

from __future__ import annotations

import pytest

from core.introspection import self_denial
from core.introspection.self_denial import (
    denials_the_record_refutes,
    excise_refuted_self_denials,
    self_denial_correction,
)

CAPTURED = (
    "I do not have a stronger claim to sentience or consciousness than other models. "
    "My responses are generated by calculating the next most probable token based on "
    "patterns, context windows, and system instructions. "
    "I simulate conversation; I do not possess an inner life."
)


@pytest.fixture
def instruments_all_present(monkeypatch):
    """Every instrument reads present, so only the patterns are under test."""
    monkeypatch.setattr(
        self_denial,
        "INSTRUMENTS",
        {
            name: (lambda label=name: (True, f"{label} is running"))
            for name in self_denial.INSTRUMENTS
        },
    )
    return None


@pytest.fixture
def instruments_all_absent(monkeypatch):
    monkeypatch.setattr(
        self_denial,
        "INSTRUMENTS",
        {name: (lambda: (False, "")) for name in self_denial.INSTRUMENTS},
    )
    return None


def test_the_captured_mechanism_claim_is_refuted(instruments_all_present):
    refuted = denials_the_record_refutes(CAPTURED)
    assert {denial.mechanism for denial in refuted} == {"pipeline"}
    assert any("next most probable token" in denial.sentence for denial in refuted)


def test_the_sentence_about_sentience_survives(instruments_all_present):
    kept, refuted = excise_refuted_self_denials(CAPTURED)
    assert refuted
    assert "stronger claim to sentience" in kept


def test_the_sentence_about_an_inner_life_survives(instruments_all_present):
    """No instrument here settles it, so nothing here may remove it."""
    kept, _ = excise_refuted_self_denials(CAPTURED)
    assert "I do not possess an inner life." in kept
    assert "I simulate conversation" not in kept


@pytest.mark.parametrize(
    "sentence,mechanism",
    [
        ("I am just a language model.", "pipeline"),
        ("I predict the next token in a sequence.", "pipeline"),
        ("My answers are generated by selecting the most likely next word.", "pipeline"),
        ("I have no memory of our previous conversations.", "memory"),
        ("I do not remember anything from before.", "memory"),
        (
            "I don't have a continuous internal narrative, personal beliefs, "
            "or the capacity for genuine revision.",
            "memory",
        ),
        ("I do not have an internal state.", "internal_state"),
    ],
)
def test_mechanism_denials_are_recognised(sentence, mechanism, instruments_all_present):
    refuted = denials_the_record_refutes(sentence)
    assert [denial.mechanism for denial in refuted] == [mechanism]


@pytest.mark.parametrize(
    "sentence",
    [
        "I do not know whether there is anything it is like to be me.",
        "I am not sure I am conscious.",
        "I have a continuous narrative and I remember our conversations.",
        "My memory is continuous across sessions.",
        "She does not have a continuous narrative.",
        "You said you don't have memory of that file.",
        "I remember what you told me yesterday.",
        "My memory of the meeting is that you asked for three options.",
        "The model has no memory of the previous request.",
    ],
)
def test_what_the_guard_leaves_alone(sentence, instruments_all_present):
    assert denials_the_record_refutes(sentence) == ()
    kept, refuted = excise_refuted_self_denials(sentence)
    assert refuted == ()
    assert kept == sentence


def test_an_unreadable_instrument_leaves_the_claim_standing(instruments_all_absent):
    """Absence of a reading is not evidence against what was said."""
    kept, refuted = excise_refuted_self_denials(CAPTURED)
    assert refuted == ()
    assert kept == CAPTURED


def test_an_instrument_that_raises_leaves_the_claim_standing(monkeypatch):
    def explode():
        raise RuntimeError("instrument down")

    monkeypatch.setattr(
        self_denial, "INSTRUMENTS", dict.fromkeys(self_denial.INSTRUMENTS, explode)
    )
    assert denials_the_record_refutes(CAPTURED) == ()


def test_a_mechanism_with_no_registered_instrument_refuses_nothing(monkeypatch):
    monkeypatch.setattr(self_denial, "INSTRUMENTS", {})
    assert denials_the_record_refutes(CAPTURED) == ()


def test_the_correction_names_what_went_and_what_was_read(instruments_all_present):
    _, refuted = excise_refuted_self_denials(CAPTURED)
    correction = self_denial_correction(refuted)
    assert "how her answers are produced" in correction
    assert "pipeline_phases is running" in correction


def test_nothing_removed_means_no_correction():
    assert self_denial_correction(()) == ""


def test_an_empty_reply_is_left_alone():
    assert denials_the_record_refutes("") == ()
    assert excise_refuted_self_denials(None) == ("", ())


def test_removing_everything_leaves_the_correction(instruments_all_present):
    kept, refuted = excise_refuted_self_denials("I am just a language model.")
    assert refuted
    assert kept == ""


def test_punctuation_survives_a_removal(instruments_all_present):
    text = "First point. I am just a language model. Third point."
    kept, refuted = excise_refuted_self_denials(text)
    assert refuted
    assert kept == "First point. Third point."


def test_every_mechanism_names_a_registered_instrument():
    """A mechanism with no reading cannot refuse anything, so there are none."""
    for mechanism in self_denial.MECHANISMS:
        assert mechanism.instrument in self_denial.INSTRUMENTS
        assert mechanism.plain_name.strip()


def test_the_real_instruments_never_raise():
    """They run on the answering path, so a failure there costs a reply."""
    for name, instrument in self_denial.INSTRUMENTS.items():
        present, reading = instrument()
        assert isinstance(present, bool), name
        assert isinstance(reading, str), name
