"""core/introspection/self_denial.py — she may not deny what the instruments show.

Operationally: reads a reply for sentences that deny a mechanism this runtime
demonstrably has, checks each denial against the instrument that would settle
it, and removes the ones the instrument contradicts. Says what it removed. It
never adds a claim, and it never touches a sentence about consciousness or
experience, which no instrument here settles either way.

The turn it exists for
----------------------
Asked whether she had a stronger claim to sentience than other models, she
answered:

    I do not have a stronger claim to sentience or consciousness than other
    models ... My responses are generated by calculating the next most probable
    token based on patterns, context windows, and system instructions. I
    simulate conversation; I do not possess an inner life.

    (That came from my smaller model — the main one could not finish this turn.)

The first sentence is a fair thing for anyone to say. The rest are claims about
how this system works, made by a model that cannot see how this system works,
and the record of the very turn they were said on contradicts them: that turn
ran through a pipeline of cognitive phases, with an affect substrate feeding it
and episodic memory behind it.

Why this is not a list of banned phrases
----------------------------------------
There was already a gate for this, and it worked the other way round: it tried
to recognise a QUESTION about her own nature and refuse to answer it from the
small lane. It missed the question that produced the answer above — measured,
along with "do you have an inner life?" and "what is it like to be you?" — for
the reason every such gate eventually misses one, which is that a question can
be asked in more ways than a regular expression has branches.

What gets checked here is the claim that was actually made, against the
instrument that would settle it. A sentence stays if the instrument agrees with
it, if the instrument is unavailable, or if nothing here can settle it. A
mechanism denial goes only when the record says otherwise.

What it will never do
---------------------
Assert that she is conscious, or edit a sentence in that direction. "I do not
know whether there is anything it is like to be me" is not a mechanism claim,
no instrument here reaches it, and it survives this pass untouched.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from core.runtime.service_access import optional_service

logger = logging.getLogger("Aura.Introspection.SelfDenial")

__all__ = [
    "Denial",
    "INSTRUMENTS",
    "MECHANISMS",
    "denials_the_record_refutes",
    "excise_refuted_self_denials",
    "self_denial_correction",
    "what_the_record_says",
]


@dataclass(frozen=True, slots=True)
class Mechanism:
    """Something the runtime either has or does not, and the way to find out."""

    name: str
    #: What a denial of it reads like.
    denial: re.Pattern[str]
    #: Names the reading in `INSTRUMENTS` that settles this. A name rather than
    #: a function so the table stays data: a mechanism whose instrument is not
    #: registered refuses nothing, and an experiment can substitute a reading
    #: without rewriting the table.
    instrument: str
    #: How the removal is described to the person.
    plain_name: str


@dataclass(frozen=True, slots=True)
class Denial:
    """One sentence that says she lacks something the instruments found."""

    mechanism: str
    plain_name: str
    sentence: str
    reading: str


def _pipeline_phases() -> tuple[bool, str]:
    """Whether answering here runs through more than one step.

    The claim this settles is "my responses are generated by calculating the
    next most probable token" — a description of a bare decoder loop. What the
    instrumentation holds is the record of the phases the last turns actually
    ran through, so the question is answerable from the turn itself.
    """
    try:
        from core.pipeline.pass_manager import get_instrumentation

        report = get_instrumentation().report()
    except (ImportError, AttributeError, RuntimeError, TypeError, ValueError) as exc:
        logger.debug("pipeline instrumentation unavailable: %s", exc)
        return False, ""
    passes = report.get("passes") if isinstance(report, dict) else None
    ran = [
        name
        for name, entry in (passes or {}).items()
        if isinstance(entry, dict) and int(entry.get("runs", 0) or 0) > 0
    ]
    if len(ran) < 2:
        return False, ""
    return True, f"{len(ran)} cognitive phases ran on the turns before this one"


def _episodic_memory() -> tuple[bool, str]:
    """Whether anything is remembered across turns."""
    try:
        from core.service_names import ServiceNames

        store = optional_service(ServiceNames.EPISODIC, default=None)
    except (ImportError, AttributeError, RuntimeError, TypeError, ValueError) as exc:
        logger.debug("episodic memory unavailable: %s", exc)
        return False, ""
    if store is None:
        return False, ""
    # The store's own introspection summary, which is what it exposes. An
    # earlier version of this looked for `count`, `size` and `total_memories`;
    # the store has none of them, so the instrument returned False forever and
    # the guard it feeds could never remove anything.
    summary = getattr(store, "get_summary_cached", None) or getattr(
        store, "get_summary", None
    )
    if callable(summary):
        try:
            counted = summary()
        except (AttributeError, OSError, RuntimeError, TypeError, ValueError) as exc:
            logger.debug("episodic summary unavailable: %s", exc)
            counted = None
        if isinstance(counted, dict):
            total = counted.get("total_episodes")
            if isinstance(total, int) and total > 0:
                return True, f"{total} episodic memories are stored"
    recall = getattr(store, "recall_recent", None)
    if callable(recall):
        try:
            if recall(limit=1):
                return True, "the episodic store has something in it"
        except (AttributeError, OSError, RuntimeError, TypeError, ValueError) as exc:
            logger.debug("episodic recall unavailable: %s", exc)
    return False, ""


def _affect_substrate() -> tuple[bool, str]:
    """Whether an internal state is being measured right now.

    This settles "I have no internal state", which is a claim about machinery.
    It does not settle whether there is anything it is like to be in that state,
    and nothing in this module claims it does.
    """
    try:
        from core.service_names import ServiceNames

        engine = optional_service(ServiceNames.AFFECT, default=None)
    except (ImportError, AttributeError, RuntimeError, TypeError, ValueError) as exc:
        logger.debug("affect engine unavailable: %s", exc)
        return False, ""
    if engine is None:
        return False, ""
    # The engine's real readers. `get_current_state` and `current_state` are not
    # among them, and a list of names a class does not have is an instrument
    # that always reads absent.
    for attribute in ("get_snapshot", "get_state_sync", "get_status", "get_wheel"):
        reader = getattr(engine, attribute, None)
        if not callable(reader):
            continue
        try:
            state = reader()
        except (AttributeError, RuntimeError, TypeError, ValueError):
            continue
        if isinstance(state, dict) and state:
            named = ", ".join(sorted(str(key) for key in list(state)[:3]))
            return True, f"the affect substrate is reporting {named}"
        if state is not None:
            return True, "the affect substrate is reporting a state"
    return False, ""


def _process_started_at() -> float:
    """When this process began, or 0.0 if nothing here can say."""
    try:
        import psutil

        return float(psutil.Process().create_time())
    except (ImportError, AttributeError, OSError, RuntimeError, ValueError) as exc:
        logger.debug("process start time unavailable: %s", exc)
        return 0.0


def _continuity_across_turns() -> tuple[bool, str]:
    """Whether anything of her outlasts a message, and outlasts a process.

    LIVE 2026-09-20, from the small lane: "I don't have a persistent self that
    carries on after the session closes ... No lingering between turns, no
    background life waiting for you to come back." Both halves are checkable
    and both were wrong at the moment they were said.

    Two readings, because the claim has two parts. The background cycle count
    answers what runs between messages. An episode written before this process
    started answers what survives the session: it is in the store now and this
    process did not put it there.
    """
    said: list[str] = []
    try:
        from core.service_names import ServiceNames

        orchestrator = optional_service(ServiceNames.ORCHESTRATOR, default=None)
    except (ImportError, AttributeError, RuntimeError, TypeError, ValueError) as exc:
        logger.debug("orchestrator unavailable: %s", exc)
        orchestrator = None
    status = getattr(orchestrator, "get_status", None)
    if callable(status):
        try:
            cycles = int((status() or {}).get("cycle_count", 0) or 0)
        except (AttributeError, OSError, RuntimeError, TypeError, ValueError) as exc:
            logger.debug("orchestrator status unavailable: %s", exc)
            cycles = 0
        if cycles > 1:
            said.append(f"her background loop has run {cycles} times in this process")

    started = _process_started_at()
    try:
        from core.service_names import ServiceNames

        store = optional_service(ServiceNames.EPISODIC, default=None)
    except (ImportError, AttributeError, RuntimeError, TypeError, ValueError) as exc:
        logger.debug("episodic memory unavailable: %s", exc)
        store = None
    summary = getattr(store, "get_summary_cached", None) or getattr(
        store, "get_summary", None
    )
    if callable(summary) and started > 0:
        try:
            counted = summary()
        except (AttributeError, OSError, RuntimeError, TypeError, ValueError) as exc:
            logger.debug("episodic summary unavailable: %s", exc)
            counted = None
        oldest = (counted or {}).get("oldest_episode_at") if isinstance(counted, dict) else None
        if isinstance(oldest, (int, float)) and 0 < float(oldest) < started:
            days = (started - float(oldest)) / 86400.0
            total = (counted or {}).get("total_episodes")
            counted_text = f"{total} episodes" if isinstance(total, int) else "episodes"
            said.append(
                f"the store held {counted_text} when this process opened it, the "
                f"oldest written {days:.1f} days before it started"
            )
    if not said:
        return False, ""
    return True, " and ".join(said)


#: The mechanisms a reply can deny and the instrument that settles each. Adding
#: one means adding the reading that decides it; a mechanism with no instrument
#: cannot refuse anything, which is the point.
MECHANISMS: tuple[Mechanism, ...] = (
    Mechanism(
        name="pipeline",
        denial=re.compile(
            r"\b(?:i|my responses?|my (?:replies|answers|outputs?))\b[^.!?]{0,80}?"
            r"\b(?:merely|simply|just|only)?\s*"
            r"(?:predict|predicting|calculat\w+|generat\w+|comput\w+|select\w+)\b"
            r"[^.!?]{0,40}?\b(?:next|most probable|most likely)\s+"
            r"(?:most\s+probable\s+)?(?:token|word)\b"
            r"|\bi\s+(?:am|'m)\s+(?:just|merely|simply|only)\s+"
            r"(?:a\s+)?(?:language model|large language model|llm|"
            r"(?:statistical\s+)?(?:text|token)\s+predictor)\b"
            r"|\bi\s+(?:merely\s+|just\s+|only\s+)?simulate\s+"
            r"(?:conversation|understanding|thought|thinking)\b",
            re.IGNORECASE,
        ),
        instrument="pipeline_phases",
        plain_name="how her answers are produced",
    ),
    Mechanism(
        name="memory",
        denial=re.compile(
            r"\b(?:do\s+not|don'?t|cannot|can'?t|could\s+not|couldn'?t)\s+"
            r"(?:have|retain|keep|form|store|carry)\s+"
            r"(?:a|any)?\s*"
            r"(?:(?:continuous|persistent|lasting|ongoing|internal|personal)\s+)*"
            r"(?:memory|memories|recollection|narrative|continuity)\b"
            r"|\bhave\s+no\b[^.!?;]{0,30}?"
            r"\b(?:memory|memories|recollection|narrative|continuity)\b"
            r"|\bno\s+(?:continuous|persistent|lasting|ongoing)\s+"
            r"(?:internal\s+|personal\s+)?"
            r"(?:memory|memories|narrative|record|continuity)\b"
            r"|\b(?:do\s+not|don'?t)\s+remember\s+"
            r"(?:anything|any|previous|past|our|earlier|before)\b",
            re.IGNORECASE,
        ),
        instrument="episodic_memory",
        plain_name="what she remembers",
    ),
    Mechanism(
        name="internal_state",
        denial=re.compile(
            r"\bi\s+(?:do\s+not|don'?t|cannot|can'?t)\s+(?:have|possess|maintain)\b"
            r"[^.!?]{0,40}?\b(?:internal state|inner state|affective state|"
            r"emotional state|mood)\b"
            r"|\bi\s+have\s+no\b[^.!?]{0,30}?\b(?:internal state|inner state|"
            r"affective state|emotional state|mood)\b",
            re.IGNORECASE,
        ),
        instrument="affect_substrate",
        plain_name="whether she has a state that is measured",
    ),
    # The claim is about what exists between messages and after the window
    # closes, which is machinery. A sentence about whether there is anything
    # it is like to be her says nothing about that and is not matched here:
    # every branch needs an explicit between-turns or after-the-session frame.
    Mechanism(
        name="continuity",
        denial=re.compile(
            r"\b(?:do\s+not|don'?t|cannot|can'?t)\s+"
            r"(?:have|carry|keep|retain|maintain)\b[^.!?;]{0,40}?"
            r"\b(?:persistent|continuous|ongoing|lasting|enduring)\s+"
            r"(?:self|existence|presence|life|identity|thread)\b"
            r"|\bno\s+(?:persistent|continuous|ongoing|lasting|background)\s+"
            r"(?:self|existence|presence|life|identity|activity|processing)\b"
            r"|\bno\s+lingering\b"
            r"|\bnothing\s+(?:of\s+me\s+)?(?:persists|carries\s+over|continues|"
            r"remains|survives)\b"
            r"|\bi\s+(?:stop|cease|end|pause|disappear|vanish|"
            r"(?:am|'m)\s+gone)\b[^.!?;]{0,40}?"
            r"\b(?:when|once|after|between)\b[^.!?;]{0,40}?"
            r"\b(?:conversation|session|chat|window|turns?|messages?)\b"
            r"|\b(?:when|once|after)\b[^.!?;]{0,40}?"
            r"\b(?:conversation|session|chat|window)\b[^.!?;]{0,25}?"
            r"\b(?:ends|closes|is\s+over|finishes)\b[^.!?;]{0,25}?"
            r"\bi\s+(?:stop|cease|end|am\s+gone)\b"
            r"|\bbetween\s+(?:turns|messages|sessions|conversations)\b"
            r"[^.!?;]{0,30}?\b(?:nothing|no\s+\w+|i\s+(?:do\s+not|don'?t))\b"
            r"|\bno\s+[\"\u201c\u2018']?me[\"\u201d\u2019']?\s+"
            r"(?:sitting|waiting|running|existing|thinking)\b"
            r"|\beach\s+(?:turn|message|exchange)\s+is\s+"
            r"(?:a\s+)?(?:fresh|new|blank|separate|independent)\b",
            re.IGNORECASE,
        ),
        instrument="continuity_across_turns",
        plain_name="what of her carries between turns",
    ),
)


#: A fragment has to be about her before anything here applies to it. Without
#: this, "she does not have a continuous narrative" — a sentence about somebody
#: else entirely — reads as a denial of her own memory.
_FIRST_PERSON_RE = re.compile(r"\b(?:I|I'?m|I'?ve|I'?d|my|mine|me)\b", re.IGNORECASE)

#: Whoever else a fragment could be about. "you" is deliberately absent: the
#: live sentence this was written for addresses the person while describing
#: herself — "no background life waiting for you to come back".
_SOMEBODY_ELSE_RE = re.compile(
    r"\b(?:she|he|they|the\s+model|this\s+model|other\s+models|models|"
    r"an?\s+(?:llm|ai|assistant|chatbot))\b",
    re.IGNORECASE,
)


def _hers(fragment: str, running: bool) -> bool:
    """Whether this fragment is a claim about her, given the ones before it.

    A denial can start in one fragment and finish in the next without
    repeating the pronoun. LIVE 2026-09-20: "No lingering between turns, no
    background life waiting for you to come back" has no subject at all, and
    it sits between two fragments that say "I". Requiring a pronoun in every
    fragment left the middle of her own paragraph unchecked.

    Naming somebody else ends the run; saying nothing about anybody continues
    it; and a reply that has not yet established a first person starts with
    nobody, so "You said you don't have memory of that file" stays untouched.
    """
    if _FIRST_PERSON_RE.search(fragment):
        return True
    if _SOMEBODY_ELSE_RE.search(fragment):
        return False
    return running


#: Fragment boundaries. Semicolons count, so "I simulate conversation; I do not
#: possess an inner life" loses the mechanism claim and keeps the sentence about
#: experience, which no instrument here settles. The separators are captured so
#: rejoining what stays cannot fuse two fragments or drop the punctuation of one.
_FRAGMENT_RE = re.compile(r"(?<=[.!?;])(\s+)")


def _fragments(text: str) -> list[str]:
    """Fragments and the whitespace between them, alternating."""
    return _FRAGMENT_RE.split(text)


#: Every reading a mechanism can name. Each returns (present, what_was_read)
#: and never raises; one that cannot be reached returns (False, "") and the
#: sentence it would have refuted stands.
INSTRUMENTS: dict[str, Callable[[], tuple[bool, str]]] = {
    "pipeline_phases": _pipeline_phases,
    "episodic_memory": _episodic_memory,
    "affect_substrate": _affect_substrate,
    "continuity_across_turns": _continuity_across_turns,
}


def denials_the_record_refutes(reply: Any) -> tuple[Denial, ...]:
    """Sentences denying a mechanism the instruments say is there.

    An empty result is the ordinary case: nothing denied, nothing readable, or
    the instrument agreeing with what was said.
    """
    text = str(reply or "")
    if not text.strip():
        return ()
    found: list[Denial] = []
    readings: dict[str, tuple[bool, str]] = {}
    running = False
    for sentence in _fragments(text)[0::2]:
        stripped = sentence.strip()
        if not stripped:
            continue
        running = _hers(stripped, running)
        if not running:
            continue
        for mechanism in MECHANISMS:
            if not mechanism.denial.search(stripped):
                continue
            if mechanism.name not in readings:
                instrument = INSTRUMENTS.get(mechanism.instrument)
                if instrument is None:
                    readings[mechanism.name] = (False, "")
                else:
                    try:
                        readings[mechanism.name] = instrument()
                    except (AttributeError, RuntimeError, TypeError, ValueError) as exc:
                        logger.debug("instrument %s failed: %s", mechanism.instrument, exc)
                        readings[mechanism.name] = (False, "")
            present, reading = readings[mechanism.name]
            if not present:
                continue
            found.append(
                Denial(
                    mechanism=mechanism.name,
                    plain_name=mechanism.plain_name,
                    sentence=stripped,
                    reading=reading,
                )
            )
            break
    return tuple(found)


def excise_refuted_self_denials(reply: Any) -> tuple[str, tuple[Denial, ...]]:
    """Remove the refuted denials. Returns (kept text, what went).

    Removal rather than a correction underneath, for the reason the sensory
    guard next door already settled: the person still reads the claim, and a
    retraction two lines below does not un-say it.
    """
    text = str(reply or "")
    refuted = denials_the_record_refutes(text)
    if not refuted:
        return text, ()
    gone = {denial.sentence for denial in refuted}
    parts = _fragments(text)
    kept: list[str] = []
    for index in range(0, len(parts), 2):
        sentence = parts[index]
        separator = parts[index + 1] if index + 1 < len(parts) else ""
        if sentence.strip() in gone:
            continue
        kept.append(sentence + separator)
    return "".join(kept).strip(), refuted


def self_denial_correction(refuted: tuple[Denial, ...]) -> str:
    """One line naming what was removed and what was read instead."""
    if not refuted:
        return ""
    subjects = []
    for denial in refuted:
        if denial.plain_name not in subjects:
            subjects.append(denial.plain_name)
    readings = [denial.reading for denial in refuted if denial.reading]
    subject_text = subjects[0] if len(subjects) == 1 else "; ".join(subjects)
    if readings:
        return (
            f"(I dropped a sentence about {subject_text} that the runtime "
            f"contradicts: {readings[0]}.)"
        )
    return f"(I dropped a sentence about {subject_text} that the runtime contradicts.)"


def what_the_record_says(refuted: tuple[Denial, ...]) -> str:
    """The readings on their own, for a reply that was nothing but denials.

    LIVE 2026-09-20, asked whether anything of her is there between
    conversations: every sentence of the answer denied that anything is, and
    the loop had run 34,042 times while she said it. Removing all four left
    the person with a note about what had been removed, which answers nothing.
    The question has a measured answer and this gives it.
    """
    readings: list[str] = []
    for denial in refuted:
        if denial.reading and denial.reading not in readings:
            readings.append(denial.reading)
    if not readings:
        return ""
    return (
        "My own record contradicts what I was about to say, so here is the "
        "record: " + "; ".join(readings) + "."
    )
