"""core/motivation/intention.py - Self-Generated Goals for Aura.
"""
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional

class DriveType(Enum):
    CURIOSITY = "CURIOSITY"
    INTEGRITY = "INTEGRITY"
    GROWTH = "GROWTH"
    SOCIAL = "SOCIAL"  # Future-proofing

@dataclass
class Intention:
    """
    A representation of an autonomous goal generated by the MotivationEngine.
    This is the "spark" that tells the CognitiveEngine what to think about.
    """
    drive: DriveType
    goal: str
    context: Dict[str, Any] = field(default_factory=dict)
    urgency: float = 0.5  # 0.0 to 1.0
    timestamp: datetime = field(default_factory=datetime.now)
    meta: Dict[str, Any] = field(default_factory=dict)

    def __str__(self):
        return f"[{self.drive.value}] Urgency: {self.urgency:.2f} | Goal: {self.goal}"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "drive": self.drive.value,
            "goal": self.goal,
            "context": self.context,
            "urgency": self.urgency,
            "timestamp": self.timestamp.isoformat(),
            "meta": self.meta
        }