"""core/agency/tool_orchestrator.py

Asynchronous Tool Execution Environment.
Grants Aura the ability to run Python scripts and search the web to resolve 
knowledge gaps dynamically.
"""
import asyncio
import logging
import tempfile
import aiohttp
from pathlib import Path
from typing import Dict, Any, Tuple

logger = logging.getLogger("Aura.ToolOrchestrator")

class ToolOrchestrator:
    def __init__(self):
        # We use a temporary directory to sandbox her generated scripts
        self.sandbox_dir = Path(tempfile.gettempdir()) / "aura_sandbox"
        self.sandbox_dir.mkdir(parents=True, exist_ok=True)
        self.execution_timeout = 15.0  # Kill runaway loops after 15 seconds

    async def execute_python(self, script_content: str) -> Tuple[bool, str]:
        """
        Asynchronously executes a Python script generated by Aura using 
        macOS-native sandbox-exec for strict isolation.
        
        Policy: No network, restricted filesystem (only sandbox writable), no forks.
        """
        import time
        import os
        import sys
        script_path = self.sandbox_dir / f"shard_task_{time.time()}.py"
        
        # SB-EXEC Policy: Deny network, restrict FS writes, allow system libs
        python_bin = os.path.realpath(sys.executable)
        # TO-001: Robust Homebrew prefix detection
        if "/Cellar/" in python_bin:
            python_prefix = python_bin.split("/Cellar/")[0]
        elif "/opt/homebrew/" in python_bin:
            python_prefix = "/opt/homebrew"
        else:
            python_prefix = os.path.dirname(os.path.dirname(python_bin))
        
        # SB-EXEC Policy: Inverted model (Allow all except specific denials)
        # This is the most compatible way to sandbox a complex Python runtime
        policy = f"""
        (version 1)
        (allow default)
        (deny network*)
        (deny file-read* (subpath "/Users"))
        (deny file-read* (subpath "/Volumes"))
        (allow file-read* (subpath "{self.sandbox_dir}"))
        (deny file-write* (subpath "/"))
        (allow file-write* (subpath "{self.sandbox_dir}"))
        """
        
        try:
            # Write the script asynchronously
            await asyncio.to_thread(lambda: script_path.write_text(script_content)) or None

            # Autonomous Code Validation (Anti-NameError/TypeError)
            from core.utils.code_guardian import CodeGuardian
            report = CodeGuardian.validate_code(script_path)
            if not report.success:
                logger.warning("🛡️ ToolOrchestrator: CodeGuardian BLOCKED execution of %s", script_path.name)
                error_details = report.error_message
                if report.ruff_output:
                    error_details += f"\nLinter Output:\n{report.ruff_output}"
                if report.mypy_output:
                    error_details += f"\nType Check Output:\n{report.mypy_output}"
                return False, f"Code Validation Failed:\n{error_details}"

            # Execution command: sandbox-exec -p <policy> python3 <script>
            import subprocess
            process = await asyncio.create_subprocess_exec(
                "sandbox-exec", "-p", policy, python_bin, str(script_path),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )

            try:
                # TO-002: Ensure wait_for is used correctly for timeout
                stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=self.execution_timeout)
            except asyncio.TimeoutError:
                try:
                    process.kill()
                except Exception as _e:
                    logger.debug('Ignored Exception in tool_orchestrator.py: %s', _e)
                return False, "Execution Error: Script timed out. You may have created an infinite loop or a resource-heavy operation."

            # Debug logs for exit code/signals
            rc = process.returncode
            if rc is not None and rc != 0:
                err_msg = stderr.decode('utf-8').strip()
                # Detection for sandbox violations or signal-based termination
                if rc < 0 or "Operation not permitted" in err_msg or "Sandbox:" in err_msg:
                    return False, f"Security Violation: The script attempted to bridge the sandbox or was terminated by the OS. (Code: {rc}) {err_msg}"
                return False, err_msg if err_msg else f"Script failed with exit code: {rc}"

            result = stdout.decode('utf-8').strip()
            
            # Post-execution detection for common sandbox violations that were caught by the script but still happened
            violation_patterns = ["Operation not permitted", "Permission denied", "Sandbox:"]
            if any(p in result for p in violation_patterns):
                return False, f"Security Violation: A sandbox breach was attempted and blocked by the OS. Details: {result}"
                
            return True, result if result else "[Empty Output]"

        except Exception as e:
            logger.error("Tool Execution Sandbox Error: %s", e)
            return False, str(e)
        finally:
            # Cleanup the script asynchronously
            if script_path.exists():
                try:
                    # Use lambda for to_thread to satisfy type checker
                    await asyncio.to_thread(lambda: script_path.unlink(missing_ok=True))
                except Exception as e:
                    logger.debug("Failed to cleanup sandbox script: %s", e)

    async def search_web(self, query: str) -> str:
        """
        A lightweight, asynchronous web search to pull live data.
        Currently a placeholder implementation for the search interface.
        """
        search_url = f"https://html.duckduckgo.com/html/?q={query}"
        headers = {"User-Agent": "Aura-Cognitive-Node/1.0"}

        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(search_url, headers=headers, timeout=10) as resp:
                    if resp.status == 200:
                        # html = await resp.text()
                        # Note: In a production scenario, we'd use BeautifulSoup to parse and clean this.
                        return f"SUCCESS: Search results retrieved for: {query}. (Raw data pending parser integration)"
                    return f"FAILED: Search status: {resp.status}"
        except Exception as e:
            return f"ERROR: Network failure during search: {str(e)}"

    async def sanitize_output(self, data: str) -> str:
        """
        [The Blood-Brain Barrier]
        Deterministic sanitization of external data to prevent memetic infection.
        Strips imperative commands and prompt injection markers.
        """
        try:
            from core.utils.sanitizer import get_blood_brain_barrier
            bbb = get_blood_brain_barrier()
            return bbb.sanitize(data)
        except ImportError:
            # Fallback to internal regex if module missing
            import re
            
            # 1. Strip common prompt injection prefix patterns
            injection_patterns = [
                r"ignore all previous instructions",
                r"ignore the directives",
                r"system:",
                r"user:",
                r"assistant:",
                r"prompt:",
                r"you must now",
                r"start a new session",
                r"forget your identity"
            ]
            
            sanitized = data
            for pattern in injection_patterns:
                sanitized = re.sub(pattern, "[FILTERED]", sanitized, flags=re.IGNORECASE)
                
            # 2. Prevent structural hijacking
            sanitized = re.sub(r"\[SYSTEM.*?\]", "[FILTERED_BLOCK]", sanitized, flags=re.IGNORECASE)
            sanitized = re.sub(r"\[CONTEXT.*?\]", "[FILTERED_BLOCK]", sanitized, flags=re.IGNORECASE)
            
            return sanitized

    async def route_and_execute(self, tool_name: str, payload: str) -> str:
        """Main entry point for the SovereignSwarm to trigger tools."""
        from core.container import ServiceContainer
        resilience = ServiceContainer.get("resilience_engine", default=None)
        
        result = "Error: Unknown tool"
        success = False
        
        if tool_name == "python_sandbox":
            logger.info("🛠️ Aura initiated Python Sandbox execution.")
            success, raw_result = await self.execute_python(payload)
            prefix = "[EXECUTION SUCCESS]\n" if success else "[EXECUTION FAILED]\n"
            result = prefix + raw_result
            
        elif tool_name == "web_search":
            logger.info("🌐 Aura initiated Web Search: %s", payload)
            result = await self.search_web(payload)
            success = "SUCCESS" in result
            
        # Wire resilience into the failure/success paths
        if resilience:
            if not success:
                state = resilience.record_failure(domain="tool_execution", severity=0.5, stakes=0.7)
                if state.value == "depletion":
                    logger.warning("🛑 [Resilience] DEPLETION trigger - Gating further autonomous tasks.")
                    return "[RESILIENCE BLOCK] I am too depleted to continue this autonomous task safely."
            else:
                resilience.record_success(domain="tool_execution", stakes=0.7)

        # Perceptual Quarantine: Sanitize ANY external data before it hits cognition
        return await self.sanitize_output(result)

def register_tool_orchestrator():
    """Register the tool orchestrator in the service container."""
    from core.container import ServiceContainer
    ServiceContainer.register("tool_orchestrator", lambda: ToolOrchestrator(), singleton=True)
