"""core/factory/pr_builder.py — Pull Request Builder.

Generates unified diffs and structures markdown changelogs/PR descriptions.
"""
from __future__ import annotations

import logging
import time
from typing import Any

logger = logging.getLogger("Aura.PRBuilder")


class PRBuilder:
    """Generates unified diffs, logs, and structures Pull Request descriptions."""

    def generate_diff_summary(self, patches: list[dict[str, Any]]) -> str:
        """Create a markdown diff summary of the software factory changes."""
        logger.info("📝 PRBuilder generating changelog/diff summary for %d patches", len(patches))

        summary_lines = []
        summary_lines.append("# Aura Autonomous Software Factory Changes")
        summary_lines.append(f"Generated at: {time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime())}\n")

        summary_lines.append("## Changed Modules")
        for i, patch in enumerate(patches, 1):
            module = patch.get("module", "unknown")
            rationale = patch.get("rationale", "No rationale provided")
            method = patch.get("method", "unknown")
            summary_lines.append(f"{i}. **{module}**")
            summary_lines.append(f"   - *Rationale:* {rationale}")
            summary_lines.append(f"   - *Method:* {method}")
            summary_lines.append("")

        summary_lines.append("## Code Diff Preview")
        for patch in patches:
            module = patch.get("module", "unknown")
            content = patch.get("patch", "")
            summary_lines.append(f"### Diff for `{module}`")
            summary_lines.append("```python")
            if content.strip():
                # Present snippet safely
                summary_lines.append(content)
            else:
                summary_lines.append("# Empty patch")
            summary_lines.append("```\n")

        return "\n".join(summary_lines)

    def build_pr_metadata(self, job_id: str, diff_summary: str, test_summary: str) -> dict[str, Any]:
        """Constructs metadata to submit a Pull Request or git commit."""
        title = f"Aura Refactor: Autonomously resolved job {job_id}"
        body = (
            f"This is an automated pull request generated by Aura.\n\n"
            f"### Execution Context\n"
            f"- Job ID: {job_id}\n"
            f"- Tests status: {test_summary}\n\n"
            f"{diff_summary}"
        )
        return {
            "title": title,
            "body": body,
            "commit_message": f"feat(aura-factory): {title}\n\nSigned-off-by: Aura Leviathan Engine",
        }
