"""core/quantum/variational.py
───────────────────────────
Parameter-shift gradients: exact derivatives of quantum expectation
values, the primitive under variational quantum algorithms (VQE/QAOA).

For any gate generated by a Pauli (RX/RY/RZ), the derivative of an
expectation is EXACTLY

    d⟨H⟩/dθ = [⟨H⟩(θ + π/2) − ⟨H⟩(θ − π/2)] / 2

— no finite-difference truncation error. The tests hold this against
closed-form derivatives and against finite differences.
"""
from __future__ import annotations

import math
from typing import Callable, Sequence

from core.quantum.statevector import QuantumCircuitError, Statevector

CircuitBuilder = Callable[[Sequence[float]], Statevector]

_SHIFT = math.pi / 2.0
MAX_PARAMETERS = 64


def expectation(build: CircuitBuilder, params: Sequence[float], pauli: str) -> float:
    state = build(list(params))
    if not isinstance(state, Statevector):
        raise QuantumCircuitError("circuit builder must return a Statevector")
    return state.expectation_pauli(pauli)


def parameter_shift_gradient(
    build: CircuitBuilder, params: Sequence[float], pauli: str
) -> list[float]:
    """Exact gradient of ⟨pauli⟩ w.r.t. every parameter via ±π/2 shifts.
    Valid for circuits whose parameters enter through RX/RY/RZ/phase-like
    Pauli rotations (the standard variational ansatz family)."""
    values = [float(p) for p in params]
    if len(values) > MAX_PARAMETERS:
        raise QuantumCircuitError(f"at most {MAX_PARAMETERS} parameters")
    gradient: list[float] = []
    for index in range(len(values)):
        plus = list(values)
        minus = list(values)
        plus[index] += _SHIFT
        minus[index] -= _SHIFT
        gradient.append(
            (expectation(build, plus, pauli) - expectation(build, minus, pauli)) / 2.0
        )
    return gradient


def gradient_descent(
    build: CircuitBuilder,
    initial: Sequence[float],
    pauli: str,
    *,
    learning_rate: float = 0.2,
    steps: int = 100,
) -> dict[str, object]:
    """Minimize ⟨pauli⟩ by exact-gradient descent — a complete, honest
    VQE loop over the simulator."""
    if not 1 <= steps <= 10_000:
        raise QuantumCircuitError("steps must be in [1, 10000]")
    params = [float(p) for p in initial]
    trajectory = [expectation(build, params, pauli)]
    for _ in range(steps):
        gradient = parameter_shift_gradient(build, params, pauli)
        params = [p - learning_rate * g for p, g in zip(params, gradient)]
        trajectory.append(expectation(build, params, pauli))
    return {
        "params": params,
        "value": trajectory[-1],
        "initial_value": trajectory[0],
        "trajectory": trajectory,
        "converged": abs(trajectory[-1] - trajectory[-2]) < 1e-9,
    }
