"""Separate private answer planning from authored public speech.

Some checkpoints emit a short metalinguistic work plan before the answer even
when their native thinking channel is disabled.  That text is neither a bad
answer nor a style defect: it belongs to a different channel.  This module
recognizes the grammatical relation (an author obligating itself to compose a
reply) and exposes a public suffix only when a clear authored suffix exists.

The parser is deliberately bounded.  It does not rewrite text, infer hidden
intent, or remove an isolated sentence that happens to discuss answering.  A
private prefix needs repeated deontic composition clauses, and the returned
answer is an exact slice of the model output.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from typing import Final

__all__ = [
    "AnswerSurfaceSplit",
    "has_private_planning_prefix",
    "split_private_planning_prefix",
]

_TOKEN_RE: Final = re.compile(r"[a-z0-9]+(?:'[a-z]+)?")
_UNIT_RE: Final = re.compile(r"\S.*?(?:[.!?](?=\s|$)|(?=\n\s*\n)|\Z)", re.DOTALL)
_DEONTIC: Final = frozenset({"must", "need", "needs", "needed", "should", "require", "requires"})
_AUXILIARY: Final = frozenset({"do", "does", "have", "has", "will", "would"})
_COMPOSITION_ACTIONS: Final = frozenset(
    {
        "address",
        "answer",
        "avoid",
        "cover",
        "explain",
        "include",
        "mention",
        "output",
        "produce",
        "provide",
        "respond",
        "return",
        "write",
    }
)
_SURFACE_OBJECTS: Final = frozenset(
    {
        "answer",
        "disclaimer",
        "disclaimers",
        "format",
        "instruction",
        "instructions",
        "part",
        "parts",
        "persona",
        "prompt",
        "reply",
        "request",
        "response",
        "user",
    }
)


@dataclass(frozen=True, slots=True)
class AnswerSurfaceSplit:
    """One replayable channel split over the exact generated bytes."""

    private_prefix: str = ""
    public_answer: str = ""
    planning_units: int = 0
    boundary_offset: int = 0

    @property
    def separated(self) -> bool:
        return bool(self.private_prefix.strip() and self.public_answer.strip())


def _normalize(value: str) -> str:
    text = unicodedata.normalize("NFKC", str(value or "")).casefold()
    text = text.replace("’", "'").replace("`", "'")
    return re.sub(r"\s+", " ", text).strip()


def _tokens(value: str) -> list[str]:
    return _TOKEN_RE.findall(_normalize(value))


def _is_composition_plan_unit(
    value: str,
    *,
    established_channel: bool = False,
) -> bool:
    """Whether one clause obligates the author to construct the reply."""

    tokens = _tokens(value)
    if len(tokens) < 2:
        return False
    action_positions = [
        index for index, token in enumerate(tokens) if token in _COMPOSITION_ACTIONS
    ]
    if not action_positions:
        return False
    action_at = action_positions[0]
    prefix = tokens[:action_at]
    deontic = any(token in _DEONTIC for token in prefix)
    subject = any(token in {"i", "we"} for token in prefix)
    auxiliary = any(token in _AUXILIARY for token in prefix)
    imperative_fragment = bool(tokens[0] in _DEONTIC)
    if not (deontic and (subject or imperative_fragment or auxiliary)):
        return False

    local = tokens[max(0, action_at - 3) : action_at + 9]
    return established_channel or bool(set(local) & _SURFACE_OBJECTS) or bool(
        set(tokens) & {"user", "request", "prompt", "persona"}
    )


def split_private_planning_prefix(text: str) -> AnswerSurfaceSplit:
    """Return an exact public suffix when a repeated private plan leads it.

    Two composition-plan clauses are required.  This keeps normal statements
    such as "We need to answer that question carefully" in public speech.  A
    split also requires substantive text after the plan; plan-only output is
    classified but never laundered into an empty answer.
    """

    body = str(text or "")
    if not body.strip():
        return AnswerSurfaceSplit()

    planning_units = 0
    boundary = 0
    saw_nonplanning = False
    for match in _UNIT_RE.finditer(body):
        unit = match.group(0)
        if _is_composition_plan_unit(
            unit,
            established_channel=planning_units > 0,
        ):
            if saw_nonplanning:
                break
            planning_units += 1
            boundary = match.end()
            continue
        if planning_units:
            boundary = match.start()
            saw_nonplanning = True
            break
        # The generated surface began as ordinary speech.  A later sentence
        # about composing text is content, not a private leading channel.
        return AnswerSurfaceSplit()

    if planning_units < 2:
        return AnswerSurfaceSplit()

    answer = body[boundary:].lstrip()
    answer_offset = len(body) - len(answer)
    if len(_tokens(answer)) < 8:
        return AnswerSurfaceSplit(
            private_prefix=body[:boundary].rstrip(),
            planning_units=planning_units,
            boundary_offset=boundary,
        )
    return AnswerSurfaceSplit(
        private_prefix=body[:answer_offset].rstrip(),
        public_answer=answer,
        planning_units=planning_units,
        boundary_offset=answer_offset,
    )


def has_private_planning_prefix(text: str) -> bool:
    """Whether generated text begins with a positively identified work plan."""

    return split_private_planning_prefix(text).planning_units >= 2
