"""core/brain/morphic_forking.py — Aura 3.0: Morphic Forking with Critic Gate
========================================================================
Implements the "critic gate" protocol: all insights generated by specialized
forks/clones must pass an epistemic consistency check before reabsorption.

Refactored for ZENITH Protocol stability:
  - Synchronous reabsorption is replaced by an async verify-then-commit flow.
  - LLM self-critic evaluation for hallucinatory dissonance.
  - Mandatory Semaphore(1) on concurrent clones to prevent M5 memory thrashing.
"""

from core.runtime.errors import record_degradation
import asyncio
import logging
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field

logger = logging.getLogger("Aura.MorphicForking")


@dataclass
class ForkInsight:
    """A cognitive fragment generated by a specialized agent fork."""
    origin_fork: str
    content: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    critic_verdict: Optional[str] = None
    is_verified: bool = False


class MorphicForkingEngine:
    """
    Manages the lifecycle of cognitive forks and their eventual reabsorption.
    
    ZENITH Purity:
      - all reabsorption goes through the _critic_gate.
      - unverified fragments are quarantined.
    """

    def __init__(self, capacity: int = 1):
        self._concurrency_limit = asyncio.Semaphore(capacity)
        self._quarantine_ledger: List[ForkInsight] = []
        self._stable_memories: List[ForkInsight] = []

    @property
    def semaphore(self) -> asyncio.Semaphore:
        return self._concurrency_limit

    async def _critic_gate(self, insight: ForkInsight) -> bool:
        """
        Executes a two-pass LLM verification on a cognitive fragment.
        1. Hallucination check.
        2. WorldModel consistency check.
        """
        from core.container import ServiceContainer
        cognition = ServiceContainer.get("cognitive_engine", default=None)
        
        if not cognition:
            logger.warning("No cognitive engine for CriticGate. Insight quarantined by default.")
            return False

        critic_prompt = (
            "Assess the following cognitive insight generated by an autonomous fork. "
            "Reject if it contains logical contradictions, hallucinatory speculative data, "
            "or violates established system principles.\n\n"
            f"INSIGHT FROM {insight.origin_fork}:\n"
            f"---CONTENT---\n{insight.content}\n---END---\n\n"
            "RESPOND with: VERDICT: ACCEPTED or VERDICT: REJECTED\n"
            "REASON: <concise reason>"
        )

        try:
            # Pass 1: Analysis
            response = await cognition.think(critic_prompt)
            verdict_text = str(response).upper()
            
            insight.critic_verdict = verdict_text
            if "VERDICT: ACCEPTED" in verdict_text:
                return True
        except Exception as e:
            record_degradation('morphic_forking', e)
            logger.error("CriticGate error: %s", e)
        
        return False

    async def absorb_insight(self, origin: str, content: str, meta: Optional[Dict] = None) -> bool:
        """
        Public entry point for fork reabsorption.
        In Zenith 3.0, absorption is NOT automatic.
        """
        insight = ForkInsight(origin_fork=origin, content=content, metadata=meta or {})
        
        logger.info("Critically evaluating insight from '%s'...", origin)
        verified = await self._critic_gate(insight)
        
        if verified:
            insight.is_verified = True
            self._stable_memories.append(insight)
            logger.info("✓ Insight ACCEPTED and absorbed.")
            # Update world model here
            return True
        else:
            self._quarantine_ledger.append(insight)
            logger.warning("! Insight REJECTED and quarantined for review.")
            return False

    def get_quarantine_stats(self) -> Dict[str, Any]:
        return {
            "quarantined_count": len(self._quarantine_ledger),
            "stable_count": len(self._stable_memories),
            "latest_rejected_forks": [i.origin_fork for i in self._quarantine_ledger[-5:]]
        }


def register_morphic_forking(orchestrator: Optional[Any] = None) -> MorphicForkingEngine:
    """Legacy registration helper expected by boot code."""
    from core.container import ServiceContainer

    engine = MorphicForkingEngine()
    ServiceContainer.register_instance("morphic_forking", engine)
    if orchestrator is not None:
        try:
            setattr(orchestrator, "morphic_forking", engine)
        except Exception as _exc:
            record_degradation('morphic_forking', _exc)
            logger.debug("Suppressed Exception: %s", _exc)
    return engine
