import ast
import logging
from typing import List

logger = logging.getLogger("Aura.ASTGuard")

class ASTGuard:
    """Validator for autogenerated Python code to prevent host compromise."""

    # Prohibited modules that and autogenerated skill should never need
    BANNED_MODULES = {
        'os', 'subprocess', 'shutil', 'socket', 'pickle', 'marshal', 
        'ctypes', 'gc', 'sys', 'builtins', 'importlib', 'pty'
    }

    # Prohibited functions/attributes
    BANNED_NAMES = {
        'eval', 'exec', 'getattr', 'setattr', 'delattr', 'hasattr',
        'globals', 'locals', 'vars', 'input', 'open', 'breakpoint', 'compile',
        '__import__', 'help'
    }

    def __init__(self):
        self.errors = []

    def validate(self, code: str) -> bool:
        """Analyzes the code for security violations."""
        self.errors = []
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            self.errors.append(f"Syntax Error: {e}")
            return False

        for node in ast.walk(tree):
            # 1. Check Imports
            if isinstance(node, ast.Import):
                for alias in node.names:
                    module_name = alias.name.split('.')[0] if alias.name else ""
                    if module_name in self.BANNED_MODULES:
                        self.errors.append(f"Forbidden Import: {module_name}")
                    
                    if alias.name and ("mycelium" in alias.name.lower() or "mycelial" in alias.name.lower()):
                        self.errors.append(f"AEGIS VIOLATION: Cannot import Ring-0 Root '{alias.name}'")

            if isinstance(node, ast.ImportFrom):
                if node.module:
                    module_name = node.module.split('.')[0]
                    if module_name in self.BANNED_MODULES:
                        self.errors.append(f"Forbidden ImportFrom: {module_name}")
                    if "mycelium" in node.module.lower():
                        self.errors.append(f"AEGIS VIOLATION: Cannot import from Ring-0 Root '{node.module}'")
                for alias in node.names:
                    if alias.name and "mycelial" in alias.name.lower():
                        self.errors.append(f"AEGIS VIOLATION: Cannot import Ring-0 Object '{alias.name}'")

            # 2. Check Name access (builtins, etc.)
            if isinstance(node, ast.Name):
                if node.id in self.BANNED_NAMES:
                    self.errors.append(f"Forbidden Name: {node.id}")
            
            # 3. Check Attribute access (e.g., cell.__import__)
            if isinstance(node, ast.Attribute):
                if node.attr.startswith('__') and not node.attr.endswith('__'):
                    # Prevent access to private attributes usually
                    pass
                if node.attr in self.BANNED_NAMES or node.attr in (
                    "__code__", "__globals__", "__closure__", "__dict__",
                    "__class__", "__subclasses__", "__mro__"
                ):
                   self.errors.append(f"Forbidden Attribute access: {node.attr}")

            # 4. Check Call (e.g. system("rm -rf /") or ServiceContainer.get("mycelial_network", default=None))
            if isinstance(node, ast.Call):
                # We check the func part
                if isinstance(node.func, ast.Name):
                    if node.func.id in self.BANNED_NAMES:
                        # Already caught by Name check, but good to be explicit
                        pass
                
                # Check for ServiceContainer.get("mycelial_network", default=None)
                if isinstance(node.func, ast.Attribute) and node.func.attr == "get":
                    if hasattr(node.func, "value") and isinstance(node.func.value, ast.Name) and node.func.value.id == "ServiceContainer":
                        if node.args and isinstance(node.args[0], ast.Constant) and "mycelial" in str(node.args[0].value).lower():
                            self.errors.append("AEGIS VIOLATION: Cannot fetch Ring-0 Root from ServiceContainer")

            # 5. Check for OOM / Resource Exhaustion (Issue 61)
            if isinstance(node, (ast.BinOp, ast.AugAssign)) and isinstance(node.op, ast.Mult):
                # Detect large list/string repetitions: [0] * 10**9 or "A" * 10**9
                if isinstance(node.right, ast.Constant) and isinstance(node.right.value, int):
                    if node.right.value > 1000000:
                        self.errors.append(f"OOM Risk: Large allocation detected ({node.right.value} multiplier)")
            
            # 6. Check for recursion (Issue 61)
            if isinstance(node, ast.FunctionDef):
                for sub_node in ast.walk(node):
                    if isinstance(sub_node, ast.Call) and isinstance(sub_node.func, ast.Name):
                        if sub_node.func.id == node.name:
                            self.errors.append(f"Recursion Risk: Skill '{node.name}' calls itself (Recursive skills forbidden)")


        if self.errors:
            for err in self.errors:
                logger.warning("Sandbox Violation: %s", err)
            return False
            
        return True

    def get_errors(self) -> List[str]:
        return self.errors