"""Hephaestus Engine for Aura.

Automates the synthesis, validation, and registration of new Python skills 
to expand Aura's capabilities autonomously.
"""
from core.runtime.errors import record_degradation
import asyncio
import inspect
import logging
import os
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional, Type

from core.base_module import AuraBaseModule
from core.container import ServiceContainer
from core.config import config
from core.resilience.resource_arbitrator import get_resource_arbitrator

SKILL_TEMPLATE = """
\"\"\"Autogenerated Skill: {name}\"\"\"
from typing import Any, Dict
from core.skills.base_skill import BaseSkill

class {class_name}(BaseSkill):
    \"\"\"{description}\"\"\"
    
    async def execute(self, params: Dict[str, Any], context: Dict[str, Any] = None) -> Dict[str, Any]:
        \"\"\"{logic_description}\"\"\"
        import asyncio
        try:
            # --- START AUTOGENERATED LOGIC ---
            async def _run():
{logic_code}
            
            return await asyncio.wait_for(_run(), timeout=30.0)
            # --- END AUTOGENERATED LOGIC ---
        except asyncio.TimeoutError:
            return {{"ok": False, "error": "Execution timed out (30s limit)"}}
        except Exception as e:
            record_degradation('hephaestus', e)
            return {{"ok": False, "error": str(e)}}
"""

class HephaestusEngine(AuraBaseModule):
    """The Forge of Capabilities."""
    
    def __init__(self):
        """Initializes the HephaestusEngine."""
        super().__init__("Hephaestus")
        self.skills_dir = config.paths.project_root / "skills"
        self.skills_dir.mkdir(parents=True, exist_ok=True)
        self.logger.info("🔨 Hephaestus Engine Online (Autogenesis Forge Ready)")

    async def synthesize_skill(self, capability_name: str, objective: str) -> Dict[str, Any]:
        """Generates a new skill from a description."""
        @self.error_boundary
        async def _synthesize_wrapped():
            self.logger.info("🔨 Forging skill: %s for objective: %s", capability_name, objective)
            
            # 0. v40: Check Growth Ladder for consent
            ladder = ServiceContainer.get("growth_ladder", default=None)
            if ladder:
                from core.self_modification.growth_ladder import ModificationLevel
                proposal = f"Autogenesis of new skill: '{capability_name}' to achieve: {objective}"
                granted = await ladder.submit_proposal(
                    level=ModificationLevel.SKILL_CREATION,
                    domain="skill_autogenesis",
                    description=proposal,
                    justification="Expanding Aura's capabilities autonomously."
                )
                if not granted:
                    self.logger.info("🚫 Hephaestus: Skill synthesis vetoed by Aura.")
                    return {"ok": False, "error": "Self-modification vetoed by Sovereign Identity core."}

            # 1. Draft Logic with LLM
            logic_data = await self._draft_logic(capability_name, objective)
            if not logic_data or not logic_data.get("ok"):
                return logic_data or {"ok": False, "error": "LLM logic generation returned empty result."}

            # 2. Assemble Code
            class_name = "".join(x.capitalize() for x in capability_name.split("_"))
            code = SKILL_TEMPLATE.format(
                name=capability_name,
                class_name=class_name,
                description=logic_data.get("description", "Autogenerated Capability"),
                logic_description=logic_data.get("logic_description", "Performs the requested task."),
                logic_code=textwrap.indent(logic_data["code"], "            ")
            )

            # 3. Path Management
            skill_file = self.skills_dir / f"{capability_name}.py"
            
            # 4. Sandbox Validation (Syntax Check)
            try:
                compile(code, str(skill_file), 'exec')
            except SyntaxError as e:
                return {"ok": False, "error": f"Syntax error in generated code: {e}"}

            # 5. Sandbox Validation (Logical Isolation)
            from core.resilience.sandbox import ASTGuard
            guard = ASTGuard()
            if not guard.validate(code):
                error_msg = f"Security validation failed for skill '{capability_name}': {', '.join(guard.get_errors())}"
                self.logger.critical("🚨 %s", error_msg)
                return {"ok": False, "error": error_msg}

            # 6. Save to Disk
            with open(skill_file, "w") as f:
                f.write(code)
                
            self.logger.info("✅ Skill '%s' forged and saved.", capability_name)
            
            # 7. Trigger Discovery
            engine = ServiceContainer.get("capability_engine", default=None)
            if engine:
                engine.reload_skills()
                
            return {"ok": True, "path": str(skill_file), "capability": capability_name}

        arbitrator = get_resource_arbitrator()
        async with arbitrator.evolution_context():
            return await _synthesize_wrapped()

    async def synthesize_logic_patch(self, target_file: str, objective: str) -> Dict[str, Any]:
        """[DEEP FORGING] Generates a logic patch for an existing core file."""
        @self.error_boundary
        async def _patch_wrapped():
            self.logger.info("🔨 Deep Forging patch for %s: %s", target_file, objective)
            
            # 0. v40: Check Growth Ladder for consent
            ladder = ServiceContainer.get("growth_ladder", default=None)
            if ladder:
                from core.self_modification.growth_ladder import ModificationLevel
                proposal = f"Deep Forging logic patch for: {target_file}. Objective: {objective}"
                granted = await ladder.submit_proposal(
                    level=ModificationLevel.CORE_PATCH,
                    domain="core_logic",
                    description=proposal,
                    justification="Optimizing core behavior for resilient operations."
                )
                if not granted:
                    self.logger.info("🚫 Hephaestus: Logic patch vetoed by Aura.")
                    return {"ok": False, "error": "Self-modification vetoed by Sovereign Identity core."}

            brain = ServiceContainer.get("cognitive_engine", default=None)

            # Read target file
            file_path = Path(target_file)
            if not file_path.exists():
                return {"ok": False, "error": f"Target file {target_file} not found."}
            
            current_code = file_path.read_text()

            prompt = (
                f"Identify a logic improvement in the following code to achieve: '{objective}'.\n"
                f"Return ONLY a JSON object with 'original_snippet' and 'replacement_snippet'.\n"
                f"Code:\n{current_code}"
            )
            
            try:
                res = await brain.think(prompt)
                self.logger.info("Deep Forge LLM response: %s", res.content)
                import json
                import ast
                # Handle potential markdown in LLM response
                content = res.content
                if "```json" in content:
                    content = content.split("```json")[1].split("```")[0]
                elif "```" in content:
                    content = content.split("```")[1].split("```")[0]
                
                try:
                    patch_data = json.loads(content.strip())
                except json.JSONDecodeError as je:
                    self.logger.error("JSON Decode failed: %s | Content: %s", je, content)
                    return {"ok": False, "error": f"Invalid JSON response from LLM: {je}"}
                
                # Apply patch to current code for validation
                original_snippet = patch_data["original_snippet"]
                replacement_snippet = patch_data["replacement_snippet"]
                
                if original_snippet not in current_code:
                    return {"ok": False, "error": "Original snippet not found in target file. Patch rejected."}
                
                patched_code = current_code.replace(original_snippet, replacement_snippet, 1)
                
                # ── Validation Gate: compile() + ASTGuard ──
                try:
                    compile(patched_code, str(file_path), 'exec')
                except SyntaxError as e:
                    self.logger.warning("🚨 Patch rejected — syntax error: %s", e)
                    return {"ok": False, "error": f"Syntax error in patched code: {e}"}
                
                from core.resilience.sandbox import ASTGuard
                guard = ASTGuard()
                if not guard.validate(patched_code):
                    error_msg = f"Security validation failed for patch: {', '.join(guard.get_errors())}"
                    self.logger.critical("🚨 %s", error_msg)
                    return {"ok": False, "error": error_msg}
                
                # ── Infinite loop detection ──
                try:
                    tree = ast.parse(replacement_snippet)
                    for node in ast.walk(tree):
                        if isinstance(node, ast.While):
                            # Check for 'while True' without a break
                            test_node = node.test
                            if isinstance(test_node, ast.Constant) and test_node.value is True:
                                has_break = any(isinstance(n, ast.Break) for n in ast.walk(node))
                                if not has_break:
                                    return {"ok": False, "error": "Patch contains 'while True' without a break statement — rejected."}
                        
                        # [Audit Fix] Detect recursion or deep nesting
                        if isinstance(node, ast.FunctionDef):
                            for inner in ast.walk(node):
                                if isinstance(inner, ast.Call) and isinstance(inner.func, ast.Name) and inner.func.id == node.name:
                                     return {"ok": False, "error": "Recursion detected in forged snippet — rejected."}

                except SyntaxError as _e:
                    logging.debug('Ignored SyntaxError in hephaestus.py: %s', _e)
                
                # ── Shadow Runtime soak test ──
                try:
                    from core.self_modification.shadow_runtime import get_shadow_runtime
                    shadow = get_shadow_runtime(str(file_path.parent.parent))
                    shadow_result = await shadow.test_mutation(
                        file_path=str(file_path.relative_to(shadow.code_base)),
                        original_code=current_code,
                        patched_code=patched_code,
                        soak_seconds=15,
                    )
                    if not shadow_result.passed:
                        self.logger.warning("🔮 Shadow test FAILED: %s", shadow_result.errors[:2])
                        return {"ok": False, "error": f"Shadow runtime test failed: {shadow_result.errors[0]}"}
                    self.logger.info("🔮 Shadow test passed (%.1fs)", shadow_result.runtime_seconds)
                except ImportError:
                    self.logger.debug("Shadow runtime not available — skipping soak test")
                except Exception as shadow_err:
                    record_degradation('hephaestus', shadow_err)
                    self.logger.warning("Shadow test error (non-blocking): %s", shadow_err)
                
                # Create a CodeFix compatible structure for SME
                from core.self_modification.code_repair import CodeFix
                fix = CodeFix(
                    target_file=str(file_path),
                    target_line=0, # SME will resolve lines from snippet
                    original_code=original_snippet,
                    fixed_code=replacement_snippet,
                    explanation=f"Deep Forge: {objective}",
                    hypothesis=f"Targeted optimization: {objective}",
                    confidence="high"
                )
                
                return {"ok": True, "fix": fix}
            except Exception as e:
                record_degradation('hephaestus', e)
                self.logger.error("Patch generation error: %s", e)
                return {"ok": False, "error": f"Patch generation failed: {e}"}

        arbitrator = get_resource_arbitrator()
        async with arbitrator.evolution_context():
            return await _patch_wrapped()

    async def _draft_logic(self, name: str, objective: str) -> Dict[str, Any]:
        """Uses the LLM to write the core execution logic for the skill."""
        brain = ServiceContainer.get("cognitive_engine", default=None)
        if not brain:
            return {"ok": False, "error": "Cognitive engine unavailable."}

        if not objective:
            objective = "Performs a general task without a specific objective provided."

        prompt = (
            f"Write a Python function body for a skill named '{name}' that accomplishes: '{objective}'.\n"
            f"Return ONLY the Python code block. No markdown, no triple backticks, no comments outside the logic.\n"
            f"The logic should be robust and return a Dict[str, Any] with 'ok' and results.\n"
            f"Import any necessary standard libraries INSIDE the logic block."
        )
        
        try:
            res = await brain.think(prompt)
            code = res.content
            # Cleanup common LLM markdown contamination
            if "```python" in code:
                code = code.split("```python")[1].split("```")[0]
            elif "```" in code:
                code = code.split("```")[1].split("```")[0]
            
            # Strip any remaining leading/trailing markdown-style comments or clutter
            lines = code.strip().split('\n')
            clean_lines = []
            for line in lines:
                if line.strip().startswith("```"): continue
                clean_lines.append(line)
            code = '\n'.join(clean_lines)

            return {
                "ok": True, 
                "code": code.strip(),
                "description": f"Autogenerated skill for {objective}",
                "logic_description": objective
            }
        except Exception as e:
            record_degradation('hephaestus', e)
            return {"ok": False, "error": f"LLM logic generation failed: {e}"}

    async def refine_skill(self, skill_name: str, objective: str) -> Dict[str, Any]:
        """[DEEP FORGING] Refactor and optimize an existing skill."""
        @self.error_boundary
        async def _refine_wrapped():
            self.logger.info("🔨 Refining existing skill: %s. Goal: %s", skill_name, objective)
            
            engine = ServiceContainer.get("capability_engine", default=None)
            if not engine or skill_name not in engine.skills:
                return {"ok": False, "error": f"Skill {skill_name} not found for refinement."}
            
            skill_file = self.skills_dir / f"{skill_name}.py"
            if not skill_file.exists():
                return {"ok": False, "error": f"Skill file {skill_file} not found."}
            
            # Use synthesize_logic_patch to generate the improvement
            patch_result = await self.synthesize_logic_patch(str(skill_file), objective)
            if not patch_result.get("ok"):
                return patch_result
            
            # Apply the patch via SME
            sme = ServiceContainer.get("self_modification_engine", default=None)
            if not sme:
                return {"ok": False, "error": "Self-Modification Engine unavailable to apply refinement."}
            
            fix = patch_result["fix"]
            success = await sme.apply_fix(fix, force=True)
            
            if success:
                self.logger.info("✅ Skill '%s' refined successfully.", skill_name)
                engine.reload_skills()
                return {"ok": True, "skill": skill_name}
            
            return {"ok": False, "error": "Failed to apply refinement patch."}

        arbitrator = get_resource_arbitrator()
        async with arbitrator.evolution_context():
            return await _refine_wrapped()

    def get_health(self) -> Dict[str, Any]:
        """Provides health info for Hephaestus."""
        return {
            **super().get_health(),
            "forge_count": len(list(self.skills_dir.glob("*.py")))
        }