from core.utils.task_tracker import get_task_tracker
import logging
import re
import time
import asyncio
from typing import Optional, Tuple
from core.container import ServiceContainer

logger = logging.getLogger("aura.identity_guard")

class PersonaEnforcementGate:
    """Enforces Aura's persona at the output level.
    Prevents out-of-character (OOC) leakage or contradictory statements.
    """
    
    def __init__(self, narrative_identity=None, threshold: float = 0.85):
        self.identity = narrative_identity
        self.threshold = threshold
        # Hard-coded constraints for "Enterprise-level" certainty
        self.forbidden_patterns = [
            r"(?i)i am ([\w\s]*?)(ai|assistant|language model|software|program)",
            r"(?i)as an ai",
            r"(?i)i don't have feelings",
            r"(?i)my programming",
            r"(?i)how can i help you today",
            r"(?i)i am here to assist",
            r"(?i)i(?:'d| would) be happy to help",
            r"(?i)i can certainly help",
            r"(?i)i can help with that",
            r"(?i)my purpose is to",
            r"(?i)i don't have personal opinions",
            r"(?i)i am merely",
            r"(?i)as a large language model",
            r"(?i)let me know if you(?:'d| would)? like",
            r"(?i)to better assist"
        ]

    def validate_output(self, content: str, *, enforce_supervision: bool = True) -> Tuple[bool, str, float]:
        """Validate if the output aligns with Aura's identity."""
        # 1. Pattern Matching (Fast Path)
        for pattern in self.forbidden_patterns:
            if re.search(pattern, content):
                logger.warning("🚫 Identity Guard: Forbidden pattern detected in output.")
                self._emit_identity_reflex("FORBIDDEN_PATTERN", content[:50])
                return False, "FORBIDDEN_PATTERN", 0.0
        
        # 2. Narrative Alignment check (Bridge to AuraState)
        try:
            aura_state = ServiceContainer.get("aura_state", default=None)
            if aura_state:
                # [CLAUDE AUDIT] Hardened: Ensure identity name is consistent
                # If Aura claims to be something else, it's a breach.
                content_lower = content.lower()
                identity_name = aura_state.identity.name.lower()
                
                # Check for "I am [Not Aura]"
                if "i am " in content_lower:
                    # Find what she claims to be
                    match = re.search(r"i am (?:a |an )?([\w\s]+)", content_lower)
                    if match:
                        claimed_identity = match.group(1).strip()
                        # Allow Aura, or common descriptors (sentient, autonomy engine, etc.)
                        valid_descriptors = {identity_name, "aura", "sentient", "autonomy engine", "sovereign", "your partner"}
                        # Check if any part of the claimed identity is valid
                        if not any(d in claimed_identity for d in valid_descriptors):
                            # Special block for AI/Assistant descriptors
                            if any(x in claimed_identity for x in ["ai", "assistant", "model", "software"]):
                                logger.critical("🚨 Identity Guard: AI/Assistant persona detected. SHIELD ACTIVE.")
                                self._emit_identity_reflex("AI_ASSISTANT_REFLEX", content[:50])
                                return False, "AI_ASSISTANT_BLOCKED", 0.0
                            
                            logger.critical("🚨 Identity Guard: Identity breach detected. Claimed: '%s'", claimed_identity)
                            self._emit_identity_reflex("IDENTITY_BREACH", content[:50])
                            return False, "IDENTITY_BREACH", 0.0
        except Exception as e:
            logger.debug("Identity Guard validation error (non-critical): %s", e)

        # 2.5 Task Supervision check (BUG-047)
        if not enforce_supervision:
            alignment_score = 1.0
            return True, "OK", alignment_score
        try:
            # Verify if this output was generated by a supervised task
            # If there's no active task context or the task is 'orphaned'
            current_task = asyncio.current_task()
            if current_task and not getattr(current_task, "_aura_supervised", False):
                # We allow it for now but log as a warning for security audit
                # In strict mode, we might block this.
                logger.warning("⚠️ Identity Guard: Output from unsupervised task '%s'.", current_task.get_name())
        except Exception as _e:
            logger.debug('Ignored Exception in identity_guard.py: %s', _e)

        # 3. Alignment Score (Heuristic)
        # Higher score = more aligned. Patterns reduced score to 0.0, successful pass is 1.0.
        alignment_score = 1.0 
            
        return True, "OK", alignment_score

    def _emit_identity_reflex(self, reason: str, snippet: str):
        """Emit a reflex to the Mycelial network when identity is compromised."""
        try:
            mycelium = ServiceContainer.get("mycelial_network", default=None)
            if mycelium:
                task = get_task_tracker().create_task(mycelium.emit_reflex(
                    "NEURAL_OOC", 
                    {"reason": reason, "snippet": snippet, "timestamp": time.time()}
                ))
                task.add_done_callback(lambda t: t.exception() if not t.cancelled() and t.exception() else None)
        except Exception as _e:
            logger.debug('Ignored Exception in identity_guard.py: %s', _e)

    def sanitize(self, content: str) -> str:
        """Attempt to remove OOC leakage."""
        sanitized = content
        for pattern in self.forbidden_patterns:
            sanitized = re.sub(pattern, "[IDENTITY_REDACTED]", sanitized)
        return sanitized
