#!/usr/bin/env python3
"""
Aura Remediation Planner
=======================

This script aggregates findings from various flagship readiness tools into a
single remediation plan.  It is designed to help developers prioritise and
address outstanding issues discovered by Aura's flagship readiness gates,
doctor, task‑ownership audits and persistence audits.  Each tool produces a
JSON report with its own schema; this planner extracts relevant sections and
combines them into a consolidated JSON document.

Usage:

    python aura_remediation_planner.py <report_directory> [--out OUTPUT]

The `<report_directory>` argument should point to a directory containing JSON
files generated by Aura's flagship tooling, such as:

 - `flagship_readiness.json` (output of `python -m core.runtime.flagship_readiness`)
 - `flagship_doctor.json`     (output of `python -m core.runtime.flagship_doctor`)
 - `task_ownership_report.json` (output of task ownership scanner)
 - `persistence_audit.json`   (output of `aura_persistence_audit.py`)

The planner scans all `.json` files in the directory and looks for keys
indicating problems (e.g. "issues", "errors", "warnings", "tasks",
"persistence") to build an aggregated set of remediation items.  It then
deduplicates entries within each category.  The resulting JSON document
contains an object whose keys are the names of the problem categories and
whose values are lists of unique remediation items.

If `--out` is provided, the aggregated result is written to that file.
Otherwise it is printed to stdout.

This tool makes no assumptions about the structure of any particular report
beyond the presence of top‑level keys containing lists of diagnostic strings.
It is therefore resilient to future changes in report formats as long as
diagnostic lists remain present.
"""

import argparse
import glob
import json
import os
import sys
from typing import Any, Dict, List, Iterable


def load_json(path: str) -> Any:
    """Load a JSON file safely.  Returns None on failure."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def extract_issues(data: Any) -> Dict[str, List[str]]:
    """Extract lists of issues from a loaded JSON object.

    The extraction is intentionally generous: any top‑level key whose value
    appears to be a list of strings and whose key name implies problems will
    be collected.  Keys matched include:
      - issues, errors, failures, warnings
      - tasks, persistence, ownership, readiness, doctor

    Returns a dictionary mapping category names to lists of issues.
    """
    categories = {
        "issues",
        "errors",
        "failures",
        "warnings",
        "tasks",
        "persistence",
        "ownership",
        "readiness",
        "doctor",
        "morphogenesis",
    }
    collected: Dict[str, List[str]] = {}
    if not isinstance(data, dict):
        return collected
    for key, value in data.items():
        key_lower = str(key).lower()
        if key_lower in categories and isinstance(value, list):
            # Flatten nested lists and cast items to strings
            items: List[str] = []
            for item in value:
                if isinstance(item, (str, int, float)):
                    items.append(str(item))
                elif isinstance(item, dict):
                    # If item is a dict, serialise as JSON string to maintain context
                    try:
                        items.append(json.dumps(item, sort_keys=True))
                    except Exception:
                        items.append(repr(item))
                else:
                    items.append(repr(item))
            collected.setdefault(key_lower, []).extend(items)
    return collected


def aggregate_reports(directory: str) -> Dict[str, List[str]]:
    """Aggregate issues from all JSON reports in a directory.

    Returns a dictionary mapping category names to deduplicated lists of
    remediation items.
    """
    aggregated: Dict[str, List[str]] = {}
    # find all JSON files
    pattern = os.path.join(os.path.abspath(directory), "*.json")
    for path in glob.glob(pattern):
        data = load_json(path)
        if data is None:
            continue
        extracted = extract_issues(data)
        for category, items in extracted.items():
            aggregated.setdefault(category, []).extend(items)
    # Deduplicate while preserving order
    for category, items in aggregated.items():
        seen: set = set()
        deduped: List[str] = []
        for item in items:
            if item not in seen:
                deduped.append(item)
                seen.add(item)
        aggregated[category] = deduped
    return aggregated


def main(argv: Iterable[str]) -> int:
    parser = argparse.ArgumentParser(description="Aggregate Aura flagship remediation reports")
    parser.add_argument(
        "directory", help="Directory containing JSON reports from Aura flagship tools"
    )
    parser.add_argument(
        "--out",
        default=None,
        help="Optional output file for aggregated JSON report.  If omitted, prints to stdout.",
    )
    args = parser.parse_args(argv)
    aggregated = aggregate_reports(args.directory)
    # Dump aggregated result
    if args.out:
        out_path = args.out
        try:
            os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
            with open(out_path, "w", encoding="utf-8") as f:
                json.dump(aggregated, f, indent=2)
        except Exception as exc:
            print(f"Failed to write output file {out_path}: {exc}", file=sys.stderr)
            return 1
    else:
        json.dump(aggregated, sys.stdout, indent=2)
        sys.stdout.write("\n")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))