#!/usr/bin/env python3
"""Write a DEPS file for every core package, from the graph that exists.

``tools/check_layering.py`` is a working clean-room ``checkdeps``, and seven
of ``core``'s 158 packages had a DEPS file. So "Aura enforces architectural
layering" was true of 4% of the tree, which is the shape an external review
named: good mechanism, partial deployment.

The seven were hand-written and say what a foundation package may not reach
for — cognition, agency, the interface. Writing 139 more of those means
inventing a layer for every package in the repository and being wrong about
some of them, which produces either false rules or a baseline full of
exceptions. This does something narrower and checkable instead.

**The rule is the graph.** For each package, the generated DEPS allows
exactly the packages that package imports today and forbids the rest of
``core``, plus ``interface``, ``skills`` and ``aura_main``. Nothing that
compiles today stops compiling, the ratchet baseline gains nothing, and every
NEW cross-package dependency becomes an edit to a DEPS file — a line in a
diff a reviewer can see, rather than an import nobody notices.

That is the property a layering rule is for. A taxonomy can be added on top
later, package by package, by replacing a generated file with a written one;
the seven existing files are exactly that and are left alone.

    python tools/generate_deps.py --check    # regenerate nothing, compare
    python tools/generate_deps.py --write
"""

from __future__ import annotations

import argparse
import ast
import json
import subprocess
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE = ROOT / "core"

#: Hand-written files, left alone. Each states an architectural intent that a
#: generated closed-world list would replace with a weaker fact.
HANDWRITTEN = {"fsw", "health", "observability", "persistence", "runtime", "utils", "verify"}

SKIP_DIRS = {"__pycache__", ".venv", "node_modules", "archive"}

#: Roots outside core that a core package must not reach into. `interface` is
#: the UI, `skills` the loadable skill tree, `aura_main` the entry point.
FORBIDDEN_ROOTS = ("interface", "skills", "aura_main")

#: Trees outside core that import core. Each gets one DEPS at its root, with
#: the same closed-world rule: what it reaches for today is allowed and the
#: rest of core is not, so a new coupling between the UI and a cognitive
#: internal is a line in a diff.
OUTSIDE_ROOTS = ("interface", "skills", "security", "llm", "executors")

OUTSIDE_HEADER = """# {root}/ — layering rules. Generated by tools/generate_deps.py.
#
# The `+` lines are the core packages this tree imports today. The `-core`
# after them forbids the rest, so a new dependency from here into a cognitive
# or runtime internal is an edit to this file. Regenerate with
# `make deps-generate`.
#
# {counted} core packages reached when this was generated.

description = "{description}"

include_rules = [
"""

HEADER = """# core/{package} — layering rules. Generated by tools/generate_deps.py.
#
# The `+` lines are what this package imports today, package by package. The
# `-core` line after them forbids the rest, so a new cross-package dependency
# is an edit to this file rather than an import nobody sees. Regenerate with
# `make deps-generate`; replace this file with a written one when this
# package earns a real architectural rule, the way core/runtime/DEPS has.
#
# {counted} outbound edges when this was generated.

description = "{description}"

include_rules = [
"""


def packages() -> list[str]:
    """Every directory under core that holds Python.

    Not "every directory with an ``__init__.py``": more than half of these are
    namespace packages — ``core/health``, ``core/media``, ``core/learning``
    and ``core/bus`` among them — and requiring the marker file made the first
    run of this generator miss them, which turned real imports into
    violations.
    """
    return sorted(
        d.name
        for d in CORE.iterdir()
        if d.is_dir() and d.name not in SKIP_DIRS and any(d.rglob("*.py"))
    )


def top_level_modules() -> set[str]:
    return {p.stem for p in CORE.glob("*.py") if p.stem != "__init__"}


def imports_by_package() -> dict[str, set[str]]:
    """Which `core.X` and outside roots each package reaches for."""
    known_packages = set(packages())
    known_modules = top_level_modules()
    found: dict[str, set[str]] = defaultdict(set)

    for path in sorted(CORE.rglob("*.py")):
        if SKIP_DIRS & set(path.parts):
            continue
        relative = path.relative_to(CORE)
        if len(relative.parts) < 2:
            continue
        package = relative.parts[0]
        if package not in known_packages:
            continue
        try:
            tree = ast.parse(path.read_text("utf-8", errors="ignore"), filename=str(path))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            modules: list[str] = []
            if isinstance(node, ast.Import):
                modules = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom) and not node.level and node.module:
                modules = [node.module]
            for module in modules:
                parts = module.split(".")
                if parts[0] != "core":
                    if parts[0] in FORBIDDEN_ROOTS:
                        found[package].add(parts[0])
                    continue
                if len(parts) == 1:
                    continue
                head = parts[1]
                if head in known_packages:
                    found[package].add(f"core.{head}")
                elif head in known_modules:
                    found[package].add(f"core.{head}")
    return found


def render(package: str, allowed: set[str]) -> str:
    inside = sorted(a for a in allowed if a.startswith("core."))
    outside = sorted(a for a in allowed if not a.startswith("core."))

    lines = [HEADER.format(
        package=package,
        counted=len(allowed),
        description=(
            f"core.{package}: may import only what it already imports; "
            "every new edge is an edit here."
        ),
    )]
    lines.append(f'    "+core.{package}",\n')
    if inside:
        lines.append("\n    # What this package reaches for today.\n")
        for name in inside:
            lines.append(f'    "+{name}",\n')
    if outside:
        lines.append(
            "\n    # Outside core. Each of these is a layering break already in\n"
            "    # the tree; recorded here so it is visible where the rule is,\n"
            "    # and so removing it is a one-line diff.\n"
        )
        for name in outside:
            lines.append(f'    "+{name}",\n')
    lines.append("\n    # Everything else.\n")
    lines.append('    "-core",\n')
    for root in FORBIDDEN_ROOTS:
        if root not in outside:
            lines.append(f'    "-{root}",\n')
    lines.append("]\n")
    return "".join(lines)


def outside_imports(root: str) -> set[str]:
    """Which `core.X` a tree outside core reaches for."""
    known_packages = set(packages())
    known_modules = top_level_modules()
    base = ROOT / root
    found: set[str] = set()
    paths = [base] if base.is_file() else list(base.rglob("*.py"))
    for path in paths:
        if SKIP_DIRS & set(path.parts):
            continue
        try:
            tree = ast.parse(path.read_text("utf-8", errors="ignore"), filename=str(path))
        except (OSError, SyntaxError):
            continue
        for node in ast.walk(tree):
            modules: list[str] = []
            if isinstance(node, ast.Import):
                modules = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom) and not node.level and node.module:
                if "." in node.module:
                    modules = [node.module]
                else:
                    modules = [f"{node.module}.{a.name}" for a in node.names]
            for module in modules:
                parts = module.split(".")
                if parts[0] != "core" or len(parts) == 1:
                    continue
                head = parts[1]
                if head in known_packages or head in known_modules:
                    found.add(f"core.{head}")
    return found


def render_outside(root: str, allowed: set[str]) -> str:
    lines = [OUTSIDE_HEADER.format(
        root=root,
        counted=len(allowed),
        description=(
            f"{root}: may import only the core packages it already imports."
        ),
    )]
    for name in sorted(allowed):
        lines.append(f'    "+{name}",\n')
    lines.append("\n    # Everything else in core.\n")
    lines.append('    "-core",\n')
    lines.append("]\n")
    return "".join(lines)


def _generated_paths() -> set[str]:
    """Every DEPS file this tool is responsible for."""
    found = {
        f"{root}/DEPS" for root in OUTSIDE_ROOTS if (ROOT / root).is_dir()
    }
    found |= {
        f"core/{package}/DEPS"
        for package in packages()
        if package not in HANDWRITTEN
    }
    return found


def _unpublished(paths: list[str]) -> list[str]:
    """Rules git does not carry are rules CI never sees.

    `.gitignore` had an unanchored `data/`, which matches a directory of that
    name at any depth — so `core/data/DEPS` was generated here, ignored by
    git, and missing in CI, where the check failed on a file it could not
    read. A generated rule that does not reach the repository is not a rule.
    """
    missing: list[str] = []
    for relative in paths:
        if not (ROOT / relative).exists():
            continue
        tracked = subprocess.run(  # noqa: S603 - fixed argv, no shell
            ["git", "ls-files", "--error-unmatch", relative],
            capture_output=True,
            cwd=ROOT,
            check=False,
        )
        if tracked.returncode != 0:
            missing.append(f"{relative} (generated but not tracked by git)")
    return missing


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    graph = imports_by_package()
    written = 0
    stale: list[str] = []

    for root in OUTSIDE_ROOTS:
        base = ROOT / root
        if not base.is_dir():
            continue
        target = base / "DEPS"
        content = render_outside(root, outside_imports(root))
        if args.check:
            if not target.exists() or target.read_text("utf-8") != content:
                stale.append(f"{root}/DEPS")
        elif args.write:
            target.write_text(content, encoding="utf-8")
            written += 1

    for package in packages():
        if package in HANDWRITTEN:
            continue
        target = CORE / package / "DEPS"
        content = render(package, graph.get(package, set()))
        if args.check:
            if not target.exists() or target.read_text("utf-8") != content:
                stale.append(f"core/{package}/DEPS")
            continue
        if args.write:
            target.write_text(content, encoding="utf-8")
            written += 1

    if args.check:
        stale.extend(_unpublished(sorted(_generated_paths())))
        if stale:
            print(f"❌ {len(stale)} DEPS file(s) do not match the import graph")
            for name in stale[:20]:
                print(f"   • {name}")
            print("\nRun `make deps-generate` in the commit that changed the imports.")
            return 1
        print(f"✅ every generated DEPS matches the graph ({len(packages())} packages)")
        return 0

    if args.write:
        print(f"wrote {written} DEPS files ({len(HANDWRITTEN)} hand-written left alone)")
        return 0

    print(json.dumps({p: sorted(v) for p, v in sorted(graph.items())}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
