#!/usr/bin/env python3
"""Which files must satisfy the whole configured lint rule set.

``pyproject.toml`` selects E, F, B, I, N, UP and ASYNC. ``make lint`` then ran
that full set over seventeen named files, and two narrower passes over
everything else: syntax errors, and four F-codes. So the configured rule set
was enforced on 0.5% of the tree and the answer to "what must new production
code satisfy" was a list somebody had to remember to edit.

It did not have to be seventeen. Measured across the 3,398 production files,
1,849 of them — 54% — already pass the full set with nothing changed. The list
was small because it was hand-curated, not because the code was dirty.

This generates it instead. The list only grows: a file that is clean joins it,
and a file already on it that stops being clean fails ``make lint`` rather than
falling off. That is the same shape as ``config/mypy_strict_files.txt`` and it
gives one answer to the question — a file you touch is a file that lints.

    python tools/ruff_strict_files.py --write     # add every clean file
    python tools/ruff_strict_files.py --check     # nothing fell off
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIST = ROOT / "config" / "ruff_strict_files.txt"

SCAN_ROOTS = (
    "core",
    "interface",
    "skills",
    "security",
    "llm",
    "executors",
    "infrastructure",
    "tools",
    # The old curated list held six test files, so tests were already in
    # scope; leaving them out here would have dropped them.
    "tests",
)
EXTRA_FILES = ("aura_main.py",)
SKIP_PARTS = {"__pycache__", ".venv", "node_modules", "archive"}


def _tracked_files() -> list[Path]:
    found: list[Path] = []
    for root in SCAN_ROOTS:
        base = ROOT / root
        if not base.is_dir():
            continue
        found.extend(
            p for p in sorted(base.rglob("*.py")) if not SKIP_PARTS & set(p.parts)
        )
    found.extend(ROOT / name for name in EXTRA_FILES if (ROOT / name).exists())
    return found


def _dirty_files(paths: list[Path]) -> set[str]:
    """Ruff's verdict on exactly these files, invoked exactly as `make lint` does.

    Passing directories and passing an explicit file list are not the same
    run: N999 resolves a module name against the path it was given, so
    ``core/data/__init__.py`` is clean when ruff walks into ``core`` and dirty
    when it is named directly inside a checkout whose directory has a hyphen
    in it. Building the list from one invocation and enforcing it with the
    other put two files on the list that `make lint` then rejected.
    """
    dirty: set[str] = set()
    chunk = 400
    for index in range(0, len(paths), chunk):
        batch = [str(p) for p in paths[index : index + chunk]]
        result = subprocess.run(  # noqa: S603 - fixed argv, no shell
            [sys.executable, "-m", "ruff", "check", "--output-format", "json", *batch],
            capture_output=True,
            text=True,
            cwd=ROOT,
            check=False,
        )
        try:
            findings = json.loads(result.stdout or "[]")
        except json.JSONDecodeError:
            print(result.stderr, file=sys.stderr)
            raise
        dirty |= {finding["filename"] for finding in findings}
    return dirty


def load() -> list[str]:
    if not LIST.exists():
        return []
    return [
        line.strip()
        for line in LIST.read_text("utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    tracked = _tracked_files()
    dirty = _dirty_files(tracked)
    clean = {str(p.relative_to(ROOT)) for p in tracked if str(p) not in dirty}
    recorded = set(load())

    if args.write:
        merged = sorted(recorded | clean)
        header = (
            "# Files that satisfy the whole configured ruff rule set\n"
            "# (pyproject [tool.ruff.lint]: E, F, B, I, N, UP, ASYNC).\n"
            "#\n"
            "# RATCHET, ONLY GROWS. Generated by tools/ruff_strict_files.py --write,\n"
            "# which adds every file that is clean and never removes one. A file\n"
            "# here that stops being clean fails `make lint`; fix it rather than\n"
            "# deleting the line. `make lint` reads this list.\n"
            f"# {len(merged)} files.\n"
        )
        LIST.write_text(header + "\n".join(merged) + "\n", encoding="utf-8")
        print(f"wrote {LIST.name}: {len(merged)} files ({len(clean - recorded)} added)")
        return 0

    missing = sorted(name for name in recorded if not (ROOT / name).exists())
    fell_off = sorted(
        name for name in recorded if str(ROOT / name) in dirty
    )
    if args.check:
        problems = []
        if missing:
            problems.append(f"{len(missing)} listed file(s) no longer exist: {missing[:5]}")
        if fell_off:
            problems.append(
                f"{len(fell_off)} listed file(s) stopped passing the rule set: "
                f"{fell_off[:5]}"
            )
        if problems:
            print("❌ ruff strict surface:")
            for problem in problems:
                print(f"   • {problem}")
            return 1
        joinable = len(clean - recorded)
        print(
            f"✅ ruff strict surface: {len(recorded)} files, all clean"
            + (f"; {joinable} more could join (--write)" if joinable else "")
        )
        return 0

    print(f"{len(recorded)} listed, {len(clean)} currently clean of {len(tracked)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
