#!/usr/bin/env python3
"""Her answers to BIG-Bench Hard, plain and through her reasoning amplifier as deployed.

G09 asks for a broad reasoning gain from her mechanisms, not a bounded
synthetic one. BIG-Bench Hard (Suzgun et al., 2022; MIT) is 27 reasoning
tasks: logical deduction, date arithmetic, tracking shuffled objects, formal
fallacies, multistep arithmetic and others. Each request is sampled evenly
across the tasks with a seed and answered in two arms:

* ``ordinary``: one greedy decode by her persona 27B through her own chat
  template, private channel open at her serving effort;
* ``amplified``: the same request through ``ReasoningAmplifierV2`` as her
  runtime calls it (``reasoning_strategies._try_amplify_v2``): task type from
  her own classifier, the live time budget ``min(45, max(8, 1.5 x
  llm_request_timeout_s))`` from her configuration, candidates generated by
  her 27B through the same template at the amplifier's temperatures. The
  run is sealed from the resident mind's state and the live batched lane,
  and every sampled generation is seeded from its prompt and temperature so a
  rerun reproduces it.

The user turn is the task's input followed by BBH's own answer form, "Let's
think step by step." in the question-answer frame of its chain-of-thought
protocol; the answer is the text after the last "the answer is" in her
public reply, normalised as BBH's targets are written. Rows are written once.

Usage:
    run_g09_bbh.py --bbh DIR --output DIR --per-task N --seed S [--arms ordinary,amplified]
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import random
import re
import sys
import threading
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

ARMS = ("ordinary", "amplified")


def request_text(example_input: str) -> str:
    """BBH's zero-shot chain-of-thought frame."""
    return f"Q: {example_input}\nA: Let's think step by step."


def extract_answer(text: str) -> str:
    """The text after the last "the answer is", trimmed as BBH targets are written."""
    body = str(text or "")
    cue = "the answer is"
    at = body.lower().rfind(cue)
    if at < 0:
        return ""
    rest = body[at + len(cue):].lstrip(" :").strip()
    if not rest:
        return ""
    answer = rest.splitlines()[0].strip()
    answer = re.sub(r"[*_`$]", "", answer).strip()
    return answer.rstrip(".").strip()


def matches(answer: str, target: str) -> bool:
    """Exact match after BBH's own looseness: case, a trailing period, an option's parentheses."""
    a, t = answer.strip().lower(), target.strip().lower()
    if a == t:
        return True
    option = re.fullmatch(r"\(([a-r])\)", t)
    if option:
        return bool(re.match(rf"^\(?{option.group(1)}\)?(\s|$|[.:,])", a))
    return False


def ordinary_row(task: dict[str, Any], decoded: dict[str, Any], seconds: float) -> dict[str, Any]:
    """One ordinary answer, graded; a reply stopped at its budget has no answer."""
    public = decoded["public_text"] if decoded["termination"] == "stop" else ""
    answer = extract_answer(public)
    return {"id": task["id"], "task": task["task"], "arm": "ordinary", "target": task["target"],
            "answer": answer, "correct": matches(answer, task["target"]),
            "seconds": round(seconds, 3), "public_text": decoded["public_text"], "detail": decoded}


def sample_tasks(bbh: Path, per_task: int, seed: int) -> list[dict[str, Any]]:
    tasks = []
    for path in sorted((bbh / "bbh").glob("*.json")):
        examples = json.loads(path.read_text(encoding="utf-8"))["examples"]
        rng = random.Random(f"{seed}:{path.stem}")
        for index in sorted(rng.sample(range(len(examples)), min(per_task, len(examples)))):
            tasks.append({"id": f"{path.stem}:{index}", "task": path.stem,
                          "input": examples[index]["input"], "target": examples[index]["target"]})
    return tasks


def live_time_budget() -> float:
    """The budget her runtime gives the amplifier (reasoning_strategies._try_amplify_v2)."""
    from core.config import config

    return min(45.0, max(8.0, float(config.llm_request_timeout_s) * 1.5))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bbh", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--per-task", type=int, required=True)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--arms", default=",".join(ARMS))
    parser.add_argument("--model", type=Path,
                        default=Path("~/.aura/models/Aura-Qwen3.8-27B-persona-crsm-7f6a2e83f73f5eef9d15"))
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--max-tokens", type=int, default=4096,
                        help="the ordinary arm's decode allowance; the amplifier's candidates keep 4096")
    parser.add_argument("--batch", type=int, default=1,
                        help="ordinary requests decoded together (tools/g12_batched.py); 1 decodes one at a time")
    args = parser.parse_args()
    if args.batch < 1:
        raise SystemExit("--batch is at least 1")
    arms = tuple(arm.strip() for arm in args.arms.split(","))
    if not arms or any(arm not in ARMS for arm in arms):
        raise SystemExit(f"--arms names arms outside {ARMS}")

    import mlx.core as mx
    from mlx_lm import load, stream_generate
    from mlx_lm.sample_utils import make_sampler

    from core.brain.llm.chat_format import (
        reasoning_effort_for_generation,
        render_chat_template,
        split_native_thinking_generation,
    )
    from core.brain.reasoning_amplifier_v2 import (
        AmplificationRequest,
        ReasoningAmplifierV2,
        classify_task_type,
    )
    from core.runtime.model_lane_control import standalone_model_lane
    from tools.run_g05_public_answers import decode_public

    tasks = sample_tasks(args.bbh.expanduser(), args.per_task, args.seed)
    if args.limit:
        tasks = tasks[: args.limit]
    output = args.output.expanduser()
    budget = live_time_budget()
    print(json.dumps({"tasks": len(tasks), "arms": arms, "amplifier_time_budget_s": budget}), flush=True)
    model_path = args.model.expanduser().resolve(strict=True)
    with standalone_model_lane(owner_id=f"g09-bbh:{output.name}", model_path=str(model_path),
                               purpose="evaluation", preemptible=False, require_exclusive=True,
                               allow_owner_eviction=True, metadata={"tool": Path(__file__).name}):
        model, tokenizer = load(str(model_path))
        generations: list[dict[str, Any]] = []
        # One model, one generation at a time: the amplifier gathers candidates
        # concurrently, and a timed-out amplify leaves its thread finishing.
        model_lock = threading.Lock()

        def sampled(prompt: str, temperature: float) -> str:
            with model_lock:
                return _sampled(prompt, temperature)

        def _sampled(prompt: str, temperature: float) -> str:
            seed = int(hashlib.sha256(f"{prompt}\0{temperature}".encode()).hexdigest()[:8], 16)
            mx.random.seed(seed)
            rendered = render_chat_template(tokenizer, [{"role": "user", "content": prompt}],
                                            add_generation_prompt=True, enable_thinking=True,
                                            reasoning_effort=reasoning_effort_for_generation(thinking=True))
            tokens = [int(t) for t in tokenizer.encode(rendered, add_special_tokens=False)]
            began, pieces = time.monotonic(), []
            for response in stream_generate(model, tokenizer, tokens, max_tokens=4096,
                                            sampler=make_sampler(temp=float(temperature))):
                pieces.append(str(response.text or ""))
            channels = split_native_thinking_generation("".join(pieces), native_thinking=True)
            generations.append({"temperature": temperature, "seconds": round(time.monotonic() - began, 3),
                                "closed": channels.boundary_closed})
            return channels.surface

        async def generate(prompt: str, temperature: float) -> str:
            return await asyncio.to_thread(sampled, prompt, temperature)

        def write_row(path: Path, row: dict[str, Any]) -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            temporary = path.with_suffix(".tmp")
            temporary.write_text(json.dumps(row, indent=1, default=str), encoding="utf-8")
            temporary.replace(path)

        def source_of(task: dict[str, Any]) -> str:
            return hashlib.sha256(task["id"].encode()).hexdigest()[:24]

        if "ordinary" in arms and args.batch > 1:
            from tools.g12_batched import decode_batch

            pending = [task for task in tasks
                       if not (output / "rows" / "ordinary" / f"{source_of(task)}.json").exists()]
            for start in range(0, len(pending), args.batch):
                group = pending[start : start + args.batch]
                conversations = [[{"role": "user", "content": request_text(task["input"])}] for task in group]
                for task, decoded in zip(group, decode_batch(model, tokenizer, conversations,
                                                             max_tokens=args.max_tokens), strict=True):
                    write_row(output / "rows" / "ordinary" / f"{source_of(task)}.json",
                              ordinary_row(task, decoded, decoded["seconds"]))
                print(json.dumps({"ordinary_batched": min(start + args.batch, len(pending)),
                                  "of": len(pending)}), flush=True)

        for done, task in enumerate(tasks, 1):
            source = source_of(task)
            text = request_text(task["input"])
            for arm in arms:
                path = output / "rows" / arm / f"{source}.json"
                if path.exists():
                    continue
                began = time.monotonic()
                if arm == "ordinary":
                    with model_lock:
                        decoded = decode_public(model, tokenizer, [{"role": "user", "content": text}],
                                                max_tokens=args.max_tokens)
                    write_row(path, ordinary_row(task, decoded, time.monotonic() - began))
                    continue
                else:
                    generations.clear()
                    amplifier = ReasoningAmplifierV2(generate)
                    request = AmplificationRequest(
                        objective=text, task_type=classify_task_type(text), time_budget_s=budget,
                        context={"sealed_evaluation": True, "read_only_evaluation": True, "skip_cache": True,
                                 "disable_batched_candidates": True},
                    )
                    try:
                        result = asyncio.run(amplifier.amplify(request))
                        public = result.answer
                        detail = {"receipt": result.receipt.to_dict(), "verified": result.verified,
                                  "confidence": result.confidence, "generations": list(generations)}
                    except TimeoutError:
                        public, detail = "", {"timed_out": True, "generations": list(generations)}
                    with model_lock:  # any generation the timeout left running ends first
                        pass
                answer = extract_answer(public)
                write_row(path, {"id": task["id"], "task": task["task"], "arm": arm, "target": task["target"],
                                 "answer": answer, "correct": matches(answer, task["target"]),
                                 "seconds": round(time.monotonic() - began, 3), "public_text": public,
                                 "detail": detail})
            print(json.dumps({"done": done, "of": len(tasks)}), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
