#!/usr/bin/env python3
"""Does keeping what she wrote make the next thing easier to write?

Experiment G, at the level of the grammar, with the one design decision that
decides whether it means anything made explicit rather than hidden.

The stream
----------
Families are not hand-picked. Each one is generated by taking a random floor
term, running it as a head over two of her words, and reading off the
correspondence it induces — so what the family wants is a term, and nobody
chose which term follows which.

Two streams, and the difference between them is the whole experiment.

  **shared**  each family's term is drawn with the terms already found offered
              as leaves, so the stream has structure a learner could carry
              forward. This is the assumption every developmental claim rests
              on, and stating it is better than smuggling it in.

  **apart**   each family's term is drawn from the bedrock alone. Nothing to
              carry. This is the negative control, and a gain here would mean
              the gain in the other stream was not about carrying anything.

Three agents
------------
  GROWN     keeps every head it writes, and offers them as leaves next time.
  RESET     is emptied between blocks.
  LESIONED  keeps the library except the head the next family was built over.

Matched: the same families in the same order, the same time budget per family,
the same search, the same words.

What is reported
----------------
Per block, how many families each agent solved and what the answers cost in
candidates walked. The compounding claim needs the gap to open as the blocks
go on, and the lesion to close it again. Anything less is reported as such.
"""

from __future__ import annotations

import argparse
import itertools
import json
import random
import statistics
import sys
import time
from dataclasses import dataclass, field
from typing import Any

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parents[1]))

from core.cognition.a_way_of_computing_she_wrote import (  # noqa: E402
    a_way_of_computing_she_wrote,
    as_a_head,
    what_each_part_says,
)
from core.cognition.an_invented_kind import WHERE_FROM  # noqa: E402
from core.cognition.the_floor_she_stands_on import (  # noqa: E402
    Code,
    OutOfFuel,
    Stuck,
    every_code,
    how_long,
    run,
)

#: What a second of the old wall-clock budget bought, measured once so the
#: campaigns keep the scale they were run at while losing the clock.
_CANDIDATES_A_SECOND_USED_TO_BUY = 20_000

#: Lengths a family is shown at. Two are fitted on and two are held back, which
#: is what a_way_of_computing_she_wrote splits them into.
AT_LENGTHS = (4, 5, 6, 7)


@dataclass
class Family:
    """A family of before-and-after states, and the term that made it."""

    transitions: list[tuple[tuple[int, ...], tuple[int, ...]]]
    over: tuple[str, str]
    from_a_term_of: int
    built_on: int = 0


@dataclass
class Agent:
    """One condition. The library is the only thing that differs."""

    name: str
    library: list[Code] = field(default_factory=list)
    solved: list[int] = field(default_factory=list)
    cost: list[list[int]] = field(default_factory=list)


def _correspondence(body: Code, first: Any, second: Any) -> dict[int, tuple[int, ...]] | None:
    """What this term says, as a source position per place, at each length."""
    found: dict[int, tuple[int, ...]] = {}
    for size in AT_LENGTHS:
        try:
            tables = (
                what_each_part_says(first, size),
                what_each_part_says(second, size),
            )
            here = (
                [int(first(at, size)) % size for at in range(size)],
                [int(second(at, size)) % size for at in range(size)],
            )
        except IndexError:
            # A word read off examples of another length refuses this one,
            # which means there is no correspondence to read at this length —
            # not that the run failed. Letting the refusal out killed the
            # developmental claim's prediction whenever any test had left a
            # word of another length in the language.
            continue
        places = []
        for at in range(size):
            try:
                said = run(
                    body,
                    (tables[1], tables[0], here[1][at], here[0][at], size, at),
                    fuel=4_000,
                )
            except (OutOfFuel, Stuck, RecursionError, TypeError, ValueError):
                return None
            if not isinstance(said, int):
                return None
            places.append(said % size)
        # A family every place answers the same way is a constant, and a
        # constant is not a rearrangement worth anything.
        if len(set(places)) < 2:
            return None
        found[size] = tuple(places)
    return found


def _a_family(rng: random.Random, library: list[Code], deepest: int) -> Family | None:
    """One family, from a term drawn at random."""
    names = sorted(WHERE_FROM)
    over = (rng.choice(names), rng.choice(names))
    first, second = WHERE_FROM[over[0]], WHERE_FROM[over[1]]
    bodies = list(
        itertools.islice(
            every_code(
                deepest=deepest, variables=6, constants=(0, 1, 2), also=tuple(library)
            ),
            4000,
        )
    )
    rng.shuffle(bodies)
    for body in bodies[:400]:
        if how_long(body) < 2:
            continue
        places = _correspondence(body, first, second)
        if places is None:
            continue
        transitions = []
        for size, wanted in places.items():
            before = tuple(range(100, 100 + size))
            transitions.append((before, tuple(before[one] for one in wanted)))
        return Family(
            transitions=transitions,
            over=over,
            from_a_term_of=how_long(body),
            built_on=sum(1 for one in library if _contains(body, one)),
        )
    return None


def _contains(body: Code, piece: Code) -> bool:
    edge = [body]
    while edge:
        here = edge.pop()
        if here == piece:
            return True
        edge.extend(here.parts)
    return False


def _attempt(agent: Agent, family: Family, within: float) -> tuple[bool, int]:
    """One agent, one family, one budget.

    The budget is a count of candidates, not a number of seconds. Two agents
    given the same seconds are not given the same search, and a result that
    moves with what else the machine is doing is not a result — measured, and
    it is why this changed: the same assertion failed twice in three runs on a
    wall clock and does not on a count.
    """
    found = a_way_of_computing_she_wrote(
        family.transitions,
        now_sayable=lambda: False,
        words=dict(WHERE_FROM),
        already=tuple(agent.library),
        most_candidates=int(within * _CANDIDATES_A_SECOND_USED_TO_BUY),
        # The recurrence route is off, and that is what makes this a
        # measurement of the library rather than of the schema. With it on,
        # every family here is solved in one candidate whatever the library
        # holds — measured, four of four in every block of every condition at
        # every budget — so the comparison has nothing to compare.
        by_recurrence=False,
    )
    if found is None:
        return False, 0
    # The library holds what she WROTE, so it can be a leaf in the next one.
    # Taking the binders off the closed head would give the fixed point it is
    # given rather than the body, which is why the body is kept beside it.
    inner = found.written
    if inner is not None and all(inner != one for one in agent.library):
        agent.library.append(inner)
    return True, found.found_at


def run_stream(
    *, stream: str, blocks: int, per_block: int, seed: int, within: float, deepest: int
) -> dict[str, Any]:
    rng = random.Random(seed)
    grown = Agent("GROWN")
    reset = Agent("RESET")
    lesioned = Agent("LESIONED")

    for block in range(blocks):
        families: list[Family] = []
        drawn_from = grown.library if stream == "shared" else []
        while len(families) < per_block:
            made = _a_family(rng, list(drawn_from), deepest)
            if made is not None:
                families.append(made)
        reset.library.clear()
        for agent in (grown, reset, lesioned):
            agent.solved.append(0)
            agent.cost.append([])
        for family in families:
            for agent in (grown, reset, lesioned):
                keep = list(agent.library)
                if agent is lesioned and agent.library:
                    # Take out the newest thing, which is what the family was
                    # most likely drawn over.
                    agent.library.pop()
                ok, cost = _attempt(agent, family, within)
                if agent is lesioned:
                    agent.library = keep
                agent.solved[-1] += 1 if ok else 0
                if ok:
                    agent.cost[-1].append(cost)
    return {
        "stream": stream,
        "seed": seed,
        "blocks": blocks,
        "per_block": per_block,
        "grown": grown.solved,
        "reset": reset.solved,
        "lesioned": lesioned.solved,
        "library": len(grown.library),
        "grown_cost": [round(statistics.mean(one), 1) if one else None for one in grown.cost],
        "reset_cost": [round(statistics.mean(one), 1) if one else None for one in reset.cost],
    }


# ── experiment F: does it carry to a family that looks nothing like it? ──


def _a_family_from(
    rng: random.Random,
    over: tuple[str, str],
    library: list[Code],
    deepest: int,
    *,
    must_contain: Code | None = None,
    must_not_contain: Code | None = None,
) -> tuple[Family, Code] | None:
    """A family whose term is drawn under a containment condition."""
    first, second = WHERE_FROM[over[0]], WHERE_FROM[over[1]]
    bodies = list(
        itertools.islice(
            every_code(
                deepest=deepest, variables=6, constants=(0, 1, 2), also=tuple(library)
            ),
            4000,
        )
    )
    rng.shuffle(bodies)
    for body in bodies[:600]:
        if how_long(body) < 2:
            continue
        if must_contain is not None and not _contains(body, must_contain):
            continue
        if must_not_contain is not None and _contains(body, must_not_contain):
            continue
        places = _correspondence(body, first, second)
        if places is None:
            continue
        transitions = []
        for size, wanted in places.items():
            before = tuple(range(100, 100 + size))
            transitions.append((before, tuple(before[one] for one in wanted)))
        return (
            Family(
                transitions=transitions,
                over=over,
                from_a_term_of=how_long(body),
            ),
            body,
        )
    return None


def run_transfer(
    *, seed: int, families: int, within: float, deepest: int
) -> dict[str, Any]:
    """One structure, learned on one surface, tested on another and on neither.

    The three domains differ in surface — a different pair of words, so the
    before-and-after states look unrelated — and in what is underneath. The
    related domain's term contains the piece she wrote on the first; the
    control's term does not contain it at all.

    Both conditions get the same families, the same budget and the same words.
    The only difference is whether the library holds what the first domain
    taught her.
    """
    rng = random.Random(seed)
    names = sorted(WHERE_FROM)
    here, there = (names[0], names[1]), (names[2], names[3])

    # The first domain, and what she writes on it.
    made = _a_family_from(rng, here, [], deepest)
    if made is None:
        return {"seed": seed, "why": "no family on the first domain"}
    first_family, latent = made
    learned = Agent("learned")
    solved, _cost = _attempt(learned, first_family, within)
    if not solved or not learned.library:
        return {"seed": seed, "why": "nothing written on the first domain"}
    piece = learned.library[-1]

    related: list[Family] = []
    apart: list[Family] = []
    while len(related) < families:
        one = _a_family_from(rng, there, [piece], deepest, must_contain=piece)
        if one is not None:
            related.append(one[0])
        elif len(related) == 0 and len(apart) == 0:
            return {"seed": seed, "why": "no related family"}
        else:
            break
    while len(apart) < families:
        one = _a_family_from(rng, there, [], deepest, must_not_contain=piece)
        if one is None:
            break
        apart.append(one[0])

    def score(pool: list[Family], library: list[Code]) -> int:
        got = 0
        for family in pool:
            agent = Agent("probe", library=list(library))
            ok, _ = _attempt(agent, family, within)
            got += 1 if ok else 0
        return got

    return {
        "seed": seed,
        "piece": how_long(piece),
        "related": len(related),
        "apart": len(apart),
        "related_with": score(related, [piece]),
        "related_without": score(related, []),
        "apart_with": score(apart, [piece]),
        "apart_without": score(apart, []),
    }


def main() -> int:
    ask = argparse.ArgumentParser(description=__doc__)
    ask.add_argument("--blocks", type=int, default=5)
    ask.add_argument("--per-block", type=int, default=6)
    ask.add_argument("--seeds", type=int, default=3)
    ask.add_argument("--within", type=float, default=4.0)
    ask.add_argument("--deepest", type=int, default=3)
    ask.add_argument("--out", default="")
    ask.add_argument("--transfer", action="store_true",
                     help="run the cross-domain check instead")
    said = ask.parse_args()

    if said.transfer:
        rows = [
            run_transfer(
                seed=2000 + seed,
                families=said.per_block,
                within=said.within,
                deepest=said.deepest,
            )
            for seed in range(said.seeds)
        ]
        usable = [one for one in rows if "why" not in one]
        for one in rows:
            print(one)
        if usable:
            print(
                "\nrelated  with %d  without %d   |   apart  with %d  without %d"
                % (
                    sum(one["related_with"] for one in usable),
                    sum(one["related_without"] for one in usable),
                    sum(one["apart_with"] for one in usable),
                    sum(one["apart_without"] for one in usable),
                )
            )
        if said.out:
            from pathlib import Path

            Path(said.out).write_text(json.dumps(rows, indent=2), encoding="utf-8")
        return 0

    began = time.monotonic()
    found: list[dict[str, Any]] = []
    for stream in ("shared", "apart"):
        for seed in range(said.seeds):
            row = run_stream(
                stream=stream,
                blocks=said.blocks,
                per_block=said.per_block,
                seed=1000 + seed,
                within=said.within,
                deepest=said.deepest,
            )
            found.append(row)
            gap = [g - r for g, r in zip(row["grown"], row["reset"])]
            print(
                f"{stream:6s} seed {row['seed']}  grown {row['grown']}  "
                f"reset {row['reset']}  lesioned {row['lesioned']}  gap {gap}  "
                f"library {row['library']}"
            )

    def gaps(stream: str) -> list[list[int]]:
        return [
            [g - r for g, r in zip(row["grown"], row["reset"])]
            for row in found
            if row["stream"] == stream
        ]

    report: dict[str, Any] = {
        "rows": found,
        "seconds": round(time.monotonic() - began, 1),
    }
    for stream in ("shared", "apart"):
        each = gaps(stream)
        by_block = [statistics.mean(one[at] for one in each) for at in range(said.blocks)]
        first, last = by_block[0], by_block[-1]
        report[stream] = {
            "gap_by_block": [round(one, 2) for one in by_block],
            "opened": round(last - first, 2),
        }
        print(f"\n{stream}: gap by block {[round(one, 2) for one in by_block]}  "
              f"opened by {round(last - first, 2)}")

    if said.out:
        from pathlib import Path

        Path(said.out).write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(f"\nwritten to {said.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
